<?php

return [
	'extensions' => [
		'layout/ui/floating-button',
		'layout/ui/empty-list',
		'layout/ui/context-menu',
		'layout/ui/snackbar-text',
		'selector/widget/factory',
		'crm:timeline/ui/*',
		'crm:timeline/services/*',
		'crm:timeline/action',
		'crm:timeline/controllers',
		'crm:timeline/item',
		'crm:timeline/stream',
		'crm:timeline/scheduler',
		'crm:document/details',
		'tasks:task',
		'loc',
		'utils/prop',
		'utils/date',
		'utils/random',
		'utils/color',
		'utils/type',
		'utils/url',
		'event-emitter',
		'rest',
		'haptics',
		'qrauth/utils',
		'alert',
		'feature',
		'utils/error-notifier',
		'notify',
		'animation/components/fade-view',
		'pull/client/events',
		'feature',
	]
];