<?php

return [
	'extensions' => [
		'layout/ui/floating-button',
		'layout/ui/empty-list',
		'layout/ui/context-menu',
		'layout/ui/widget-header-button',
		'layout/ui/snackbar-text',
		'selector/widget/factory',

		'crm:timeline/ui/banner',
		'crm:timeline/ui/divider',
		'crm:timeline/ui/reminder',
		'crm:timeline/ui/sticky-date',
		'crm:timeline/ui/text-editor',
		'crm:timeline/ui/textarea',
		'crm:timeline/ui/toolbar',

		'crm:timeline/services/activity-viewer',
		'crm:timeline/services/data-provider',
		'crm:timeline/services/file-selector-configs',
		'crm:timeline/services/push-processor',

		'crm:timeline/action',
		'crm:timeline/controllers',
		'crm:timeline/item',
		'crm:timeline/stream',
		'crm:timeline/scheduler',
		'crm:document/details',
		'tasks:task',
		'loc',
		'utils/prop',
		'utils/date',
		'utils/random',
		'utils/color',
		'utils/type',
		'utils/url',
		'utils/file',
		'event-emitter',
		'rest',
		'haptics',
		'qrauth/utils',
		'alert',
		'feature',
		'utils/error-notifier',
		'notify',
		'animation/components/fade-view',
		'pull/client/events',
		'feature',
	],
];