
CREATE TABLE b_imconnectors_status (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONNECTOR varchar(255) NOT NULL,
  LINE varchar(255) NOT NULL,
  ACTIVE varchar(1) NOT NULL,
  CONNECTION varchar(1) NOT NULL,
  ERROR varchar(1) NOT NULL,
  REGISTER varchar(1) NOT NULL,
  DATA text,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imconnectors_status_connector_line ON b_imconnectors_status (connector, line);
CREATE INDEX ix_b_imconnectors_status_line ON b_imconnectors_status (line);

CREATE TABLE b_imconnectors_custom_connectors (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ID_CONNECTOR varchar(255),
  NAME varchar(255),
  ICON text,
  ICON_DISABLED text,
  COMPONENT text,
  DEL_EXTERNAL_MESSAGES varchar(2),
  EDIT_INTERNAL_MESSAGES varchar(2),
  DEL_INTERNAL_MESSAGES varchar(2),
  NEWSLETTER varchar(2),
  NEED_SYSTEM_MESSAGES varchar(2),
  NEED_SIGNATURE varchar(2),
  CHAT_GROUP varchar(2),
  REST_APP_ID int,
  REST_PLACEMENT_ID int,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_imconnectors_custom_connectors_id_connector ON b_imconnectors_custom_connectors (id_connector);

CREATE TABLE b_imconnectors_info_connectors (
  LINE_ID int,
  DATA text,
  EXPIRES timestamp,
  DATA_HASH varchar(32) NOT NULL,
  PRIMARY KEY (LINE_ID)
);

CREATE TABLE b_imconnectors_chat_last_message (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  EXTERNAL_CHAT_ID varchar(255) NOT NULL,
  CONNECTOR varchar(255) NOT NULL,
  EXTERNAL_MESSAGE_ID varchar(255),
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imconnectors_chat_last_message_external_chat_id_connector ON b_imconnectors_chat_last_message (external_chat_id, connector);

CREATE TABLE b_imconnectors_delivery_mark (
  MESSAGE_ID int8 NOT NULL,
  CHAT_ID int8 NOT NULL,
  DATE_CREATE timestamp NOT NULL,
  PRIMARY KEY (MESSAGE_ID)
);
CREATE INDEX ix_b_imconnectors_delivery_mark_chat_id ON b_imconnectors_delivery_mark (chat_id);
