CREATE TABLE b_recyclebin (
      ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      NAME varchar(255),
      SITE_ID char(2),
      ENTITY_ID varchar(64) NOT NULL,
      MODULE_ID varchar(64) NOT NULL,
      ENTITY_TYPE varchar(64) NOT NULL,
      TIMESTAMP timestamp NOT NULL,
      USER_ID int8,
      PRIMARY KEY (ID)
);
CREATE INDEX ix_b_recyclebin_user_id ON b_recyclebin (user_id);
CREATE INDEX ix_b_recyclebin_module_id ON b_recyclebin (module_id);
CREATE INDEX ix_b_recyclebin_entity_type ON b_recyclebin (entity_type);
CREATE INDEX ix_b_recyclebin_timestamp ON b_recyclebin (timestamp);
CREATE INDEX ix_b_recyclebin_entity_id ON b_recyclebin (entity_id);

CREATE TABLE b_recyclebin_data (
      ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      RECYCLEBIN_ID int8 NOT NULL,
      ACTION varchar(64) NOT NULL,
      DATA bytea NOT NULL,
      PRIMARY KEY (ID)
);
CREATE INDEX ix_b_recyclebin_data_recyclebin_id ON b_recyclebin_data (recyclebin_id);

CREATE TABLE b_recyclebin_files (
      ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      RECYCLEBIN_ID int8 NOT NULL,
      FILE_ID int8 NOT NULL,
      STORAGE_TYPE varchar(64),
      PRIMARY KEY (ID)
);
CREATE INDEX ix_b_recyclebin_files_recyclebin_id ON b_recyclebin_files (recyclebin_id);
CREATE INDEX ix_b_recyclebin_files_file_id ON b_recyclebin_files (file_id);