
CREATE TABLE b_market_tag (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  MODULE_ID varchar(32) NOT NULL,
  TYPE char(1) NOT NULL,
  CODE varchar(32) NOT NULL,
  DATE_VALUE date NOT NULL,
  VALUE varchar(32) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_market_tag_type_module_id_code_date_value ON b_market_tag (type, module_id, code, date_value);
CREATE INDEX ix_b_market_tag_type_module_id_code ON b_market_tag (type, module_id, code);

CREATE TABLE b_market_app_favorites (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  APP_CODE varchar(128) NOT NULL,
  USER_ID int NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_market_app_favorites_user_id ON b_market_app_favorites (user_id);
