<?php

return [
	'extensions' => [
		'type',
		'loc',
		'haptics',
		'in-app-url',
		'notify-manager',
		'utils/object',
		'utils/function',
		'utils/uuid',
		'utils/url',
		'im:lib/theme',
		'im:messenger/assets/common',
		'im:messenger/lib/di/service-locator',
		'im:messenger/const',
		'im:messenger/controller/file-download-menu',
		'im:messenger/controller/reaction-viewer',
		'im:messenger/controller/user-profile',
		'im:messenger/lib/converter',
		'im:messenger/lib/counters',
		'im:messenger/lib/date-formatter',
		'im:messenger/lib/emitter',
		'im:messenger/lib/logger',
		'im:messenger/lib/helper',
		'im:messenger/lib/params',
		'im:messenger/lib/element',
		'im:messenger/lib/parser',
		'im:messenger/lib/utils',
		'im:messenger/lib/permission-manager',
		'im:messenger/lib/integration/immobile/calls',
		'im:messenger/lib/ui/notification',
		'im:messenger/provider/rest',
		'im:messenger/provider/service',
		'im:messenger/view/dialog',
		'im:messenger/controller/dialog/lib/mention',
		'im:messenger/controller/dialog/lib/draft-manager',
		'im:messenger/controller/dialog/lib/header',
		'im:messenger/controller/dialog/lib/reply-manager',
		'im:messenger/controller/dialog/lib/scroll-manager',
		'im:messenger/controller/dialog/lib/message-renderer',
		'im:messenger/controller/dialog/lib/audio-message-player',
		'im:messenger/controller/dialog/lib/message-avatar-menu',
		'im:messenger/controller/dialog/lib/web',
		'im:messenger/controller/dialog/lib/locator',
		'im:messenger/controller/dialog/lib/message-menu',
		'im:messenger/controller/dialog/lib/pin',
		
	],
	'bundle' => [
		'./src/dialog',
	],
];