<?php

return [
	'extensions' => [
		'type',
	],
	'bundle' => [
		'./src/analytics',
		'./src/attach',
		'./src/app-status',
		'./src/bot',
		'./src/connection-status',
		'./src/event-type',
		'./src/feature-flag',
		'./src/recent',
		'./src/rest',
		'./src/user',
		'./src/color',
		'./src/message',
		'./src/dialog-type',
		'./src/dialog-action-type',
		'./src/sidebar-action-type',
		'./src/file-type',
		'./src/file-status',
		'./src/reaction-type',
		'./src/path',
		'./src/draft',
		'./src/search',
		'./src/error',
		'./src/bb-code',
		'./src/setting',
		'./src/sidebar',
		'./src/promo',
		'./src/copilot-button',
		'./src/component-code',
		'./src/header-button',
		'./src/cache',
		'./src/navigation-tab',
		'./src/keyboard',
		'./src/waiting-entity',
		'./src/open-request',
		'./src/context-type',
		'./src/url-params',
		'./src/messenger-init-rest',
	],
];
