<?php

return [
	'extensions' => [
		'loc',
		'rest',
		'alert',
		'haptics',
		'apptheme',
		'animation',
		'assets/icons',
		'assets/icons/types',
		'elements-stack',
		'utils/url',
		'utils/object',
		'utils/random',
		'utils/function',
		'utils/validation',
		'selector/widget/factory',
		'layout/ui/checkbox',
		'layout/ui/scroll-view',
		'layout/pure-component',
		'layout/ui/fields/file',
		'layout/ui/context-menu',
		'layout/ui/empty-screen',
		'layout/ui/user/avatar',
		'layout/ui/user-selection-manager',
		'layout/list-view-queue-worker',

		'ui-system/blocks/icon',
		'ui-system/blocks/chip',
		'ui-system/form/checkbox',

		'tasks:checklist',
		'tasks:checklist/flat-tree',
		'tasks:layout/checklist/list',
		'tasks:checklist/flat-tree/item',
	],
	'bundle' => [
		'./src/item/base-item',
		'./src/item/main-item',
		'./src/item/root-item',
		'./src/menu/actions-menu',
		'./src/menu/checklists-menu',
		'./src/list-item/menu',
		'./src/layout/item-view',
		'./src/depth-dots',
		'./src/text-field',
		'./src/add-button',
		'./src/constants',
		'./src/buttons/button-add-checklist',
		'./src/buttons/button-add-item',
		'./src/buttons/button-remove',
		'./src/checkbox/checkbox-counter',
		'./src/checkbox/important',
		'./src/checkbox/progress',
		'./src/actions/members',
		'./src/actions/attachments',
		'./src/empty-screen',
	],
];
