<?php

return [
	'extensions' => [
		'loc',
		'rest',
		'alert',
		'haptics',
		'animation',
		'assets/icons',
		'assets/icons/types',
		'notify-manager',
		'utils/url',
		'toast/base',
		'utils/object',
		'utils/random',
		'utils/function',
		'utils/validation',
		'layout/ui/menu',
		'layout/ui/checkbox',
		'layout/ui/scroll-view',
		'layout/pure-component',
		'layout/ui/fields/user',
		'layout/ui/fields/file',
		'layout/ui/context-menu',
		'layout/ui/optimized-list-view',
		'layout/list-view-queue-worker',

		'ui-system/blocks/icon',
		'ui-system/form/checkbox',
		'ui-system/typography/text',
		'ui-system/blocks/avatar-stack',
		'ui-system/typography/text-input',

		'tariff-plan-restriction',
		'tasks:enum',
		'tasks:checklist',
		'tasks:checklist/flat-tree',
		'tasks:layout/checklist/list',
		'tasks:checklist/flat-tree/item',
		'tasks:tariff-plan-restriction',
		'tasks:layout/task/form-utils'
	],
	'bundle' => [
		'./src/item/base-item',
		'./src/item/main-item',
		'./src/item/root-item',
		'./src/menu/actions-menu',
		'./src/menu/checklists-menu',
		'./src/list-item/menu',
		'./src/layout/item-view',
		'./src/depth-dots',
		'./src/text-field',
		'./src/add-button',
		'./src/constants',
		'./src/toasts',
		'./src/buttons/button-add-checklist',
		'./src/buttons/button-add-item',
		'./src/buttons/button-remove',
		'./src/checkbox/checkbox-counter',
		'./src/checkbox/important',
		'./src/checkbox/progress',
		'./src/actions/members',
		'./src/actions/attachments',
	],
];
