<?php

namespace Bitrix\Call\Integration\AI;

class CallAIError extends \Bitrix\Call\Error
{
	public const
		AI_UNAVAILABLE_ERROR = 'AI_UNAVAILABLE_ERROR',
		AI_SETTINGS_ERROR = 'AI_SETTINGS_ERROR',
		AI_AGREEMENT_ERROR = 'AI_AGREEMENT_ERROR',
		AI_TARIFF_ERROR = 'AI_TARIFF_ERROR',
		AI_UNSUPPORTED_TRACK_ERROR = 'AI_UNSUPPORTED_TRACK_ERROR',
		AI_EMPTY_PAYLOAD_ERROR = 'AI_EMPTY_PAYLOAD_ERROR',
		AI_UNRECOGNIZED_PAYLOAD_ERROR = 'AI_UNRECOGNIZED_PAYLOAD_ERROR',
		AI_NOT_ENOUGH_BAAS_ERROR = 'AI_NOT_ENOUGH_BAAS_ERROR'
	;
}
