CREATE TABLE IF NOT EXISTS b_booking_client_type (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MODULE_ID varchar(255) NOT NULL,
	CODE varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_client_type_module_id_code ON b_booking_client_type (module_id, code);

CREATE TABLE IF NOT EXISTS b_booking_resource_type (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MODULE_ID varchar(255) NOT NULL,
	CODE varchar(255) DEFAULT NULL,
	NAME varchar(255) DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_resource_type_module_id_code ON b_booking_resource_type (module_id, code);

CREATE TABLE IF NOT EXISTS b_booking_resource_type_notification_settings (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	TYPE_ID int8 NOT NULL,
	IS_INFO_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_INFO varchar(255) NOT NULL,
	IS_CONFIRMATION_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_CONFIRMATION varchar(255) NOT NULL,
	IS_REMINDER_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_REMINDER varchar(255) NOT NULL,
	IS_FEEDBACK_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_FEEDBACK varchar(255) NOT NULL,
	IS_DELAYED_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_DELAYED varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_booking_resource (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	TYPE_ID int8 NOT NULL,
	EXTERNAL_ID int8 DEFAULT NULL,
	IS_MAIN char(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_resource_type_id ON b_booking_resource (type_id);
CREATE INDEX ix_b_booking_resource_external_id ON b_booking_resource (external_id);
CREATE INDEX ix_b_booking_resource_is_main ON b_booking_resource (is_main);

CREATE TABLE IF NOT EXISTS b_booking_resource_data (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	NAME varchar(255) NOT NULL,
	DESCRIPTION text,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY int8 NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_resource_data_resource_id ON b_booking_resource_data (resource_id);

CREATE TABLE IF NOT EXISTS b_booking_resource_settings (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	WEEKDAYS varchar(50) NOT NULL,
	SLOT_SIZE int8 DEFAULT NULL,
	TIME_FROM int8 NOT NULL,
	TIME_TO int8 NOT NULL,
	TIMEZONE varchar(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_notification_settings (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	IS_INFO_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_INFO varchar(255) NOT NULL,
	IS_CONFIRMATION_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_CONFIRMATION varchar(255) NOT NULL,
	IS_REMINDER_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_REMINDER varchar(255) NOT NULL,
	IS_FEEDBACK_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_FEEDBACK varchar(255) NOT NULL,
	IS_DELAYED_ON char(1) NOT NULL DEFAULT 'Y',
	TEMPLATE_TYPE_DELAYED varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_booking_booking (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	NAME varchar(255) DEFAULT NULL,
	DATE_FROM int8 NOT NULL,
	DATE_TO int8 NOT NULL,
	TIMEZONE_FROM varchar(50) NOT NULL,
	TIMEZONE_FROM_OFFSET int NOT NULL,
	TIMEZONE_TO varchar(50) NOT NULL,
	TIMEZONE_TO_OFFSET int NOT NULL,
	DATE_MAX int8 NOT NULL,
	IS_RECURRING char(1) NOT NULL DEFAULT 'N',
	RRULE text,
	PARENT_ID int8 DEFAULT NULL,
	IS_DELETED char(1) NOT NULL DEFAULT 'N',
	IS_CONFIRMED char(1) NOT NULL DEFAULT 'N',
	DESCRIPTION text,
	VISIT_STATUS varchar(20) NOT NULL DEFAULT 'unknown',
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY int8 NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_date_from_date_max ON b_booking_booking (date_from, date_max);
CREATE INDEX ix_b_booking_booking_date_from_date_to ON b_booking_booking (date_from, date_to);
CREATE INDEX ix_b_booking_booking_date_from ON b_booking_booking (date_from);
CREATE INDEX ix_b_booking_booking_date_max ON b_booking_booking (date_max);
CREATE INDEX ix_b_booking_booking_is_deleted ON b_booking_booking (is_deleted);
CREATE INDEX ix_b_booking_booking_parent_id ON b_booking_booking (parent_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_resource (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_booking_resource_booking_id_resource_id ON b_booking_booking_resource (booking_id, resource_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_client (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	CLIENT_TYPE_ID int8 NOT NULL,
	CLIENT_ID int8 NOT NULL,
	IS_PRIMARY char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_booking_client_booking_id_client_type_id_client_id ON b_booking_booking_client (booking_id, client_type_id, client_id);
CREATE INDEX ix_b_booking_booking_client_client_type_id_client_id ON b_booking_booking_client (client_type_id, client_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_external_data (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	MODULE_ID varchar(255) NOT NULL,
	ENTITY_TYPE_ID varchar(255) NOT NULL,
	VALUE varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_external_data_booking_id ON b_booking_booking_external_data (booking_id);
CREATE INDEX ix_b_booking_booking_external_data_module_id_entity_type_id_val ON b_booking_booking_external_data (module_id, entity_type_id, value);

CREATE TABLE IF NOT EXISTS b_booking_journal (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ENTITY_ID int8 NOT NULL,
	TYPE varchar(64) NOT NULL,
	DATA text NOT NULL,
	STATUS varchar(10) NOT NULL,
	INFO varchar(512) NOT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_journal_entity_id ON b_booking_journal (entity_id);
CREATE INDEX ix_b_booking_journal_type ON b_booking_journal (type);
CREATE INDEX ix_b_booking_journal_status ON b_booking_journal (status);
CREATE INDEX ix_b_booking_journal_created_at ON b_booking_journal (created_at);

CREATE TABLE IF NOT EXISTS b_booking_favorites (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MANAGER_ID int8 NOT NULL,
	RESOURCE_ID int8 NOT NULL,
	TYPE varchar(10) NOT NULL DEFAULT 'ADDED',
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_favorites_resource_id ON b_booking_favorites (resource_id);
CREATE UNIQUE INDEX ux_b_booking_favorites_manager_id_resource_id ON b_booking_favorites (manager_id, resource_id);

CREATE TABLE IF NOT EXISTS b_booking_scorer (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL DEFAULT 0,
	ENTITY_ID int NOT NULL DEFAULT 0,
	TYPE varchar(64) NOT NULL DEFAULT '',
	VALUE int8 NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_scorer_user_id_entity_id_type ON b_booking_scorer (user_id, entity_id, type);
CREATE INDEX ix_b_booking_scorer_user_id ON b_booking_scorer (user_id);
CREATE INDEX ix_b_booking_scorer_type ON b_booking_scorer (type);
CREATE INDEX ix_b_booking_scorer_entity_id ON b_booking_scorer (entity_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_note (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	DESCRIPTION text NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_booking_note_booking_id ON b_booking_booking_note (booking_id);

CREATE TABLE IF NOT EXISTS b_booking_option (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL,
	NAME varchar(255) NOT NULL,
	VALUE varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_booking_option_user_id_name ON b_booking_option (user_id, name);

CREATE TABLE IF NOT EXISTS b_booking_booking_message (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	NOTIFICATION_TYPE varchar(255) NOT NULL,
	SENDER_MODULE_ID varchar(255) NOT NULL,
	SENDER_CODE varchar(255) NOT NULL,
	EXTERNAL_MESSAGE_ID int8 NOT NULL,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_message_booking_id_notification_type_sende ON b_booking_booking_message (booking_id, notification_type, sender_module_id, sender_code, created_at);
CREATE INDEX ix_b_booking_booking_message_sender_module_id_sender_code_exter ON b_booking_booking_message (sender_module_id, sender_code, external_message_id);

CREATE TABLE IF NOT EXISTS b_booking_booking_message_failure_log (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOOKING_ID int8 NOT NULL,
	NOTIFICATION_TYPE varchar(255) NOT NULL,
	SENDER_MODULE_ID varchar(255) NOT NULL,
	SENDER_CODE varchar(255) NOT NULL,
	REASON_CODE varchar(255) NOT NULL,
	REASON_TEXT text,
	CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_booking_booking_message_failure_log_booking_id_notificatio ON b_booking_booking_message_failure_log (booking_id, notification_type, sender_module_id, sender_code, created_at);
