CREATE TABLE b_xdi_lf_scheme (
      ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      LID char(2) NOT NULL,
      TYPE varchar(100) NOT NULL,
      NAME varchar(255) NOT NULL,
      SORT int NOT NULL DEFAULT 100,
      ACTIVE char(1) NOT NULL DEFAULT 'Y',
      AUTO char(1) NOT NULL DEFAULT 'N',
      ENABLE_COMMENTS char(1) DEFAULT 'Y',
      DAYS_OF_MONTH varchar(100),
      DAYS_OF_WEEK varchar(15),
      TIMES_OF_DAY varchar(255),
      LAST_EXECUTED timestamp,
      HOST varchar(255),
      PORT varchar(5),
      PAGE varchar(255),
      URI text,
      METHOD varchar(255),
      PARAMS varchar(255),
      LOGIN varchar(255),
      PASSWORD varchar(255),
      ENTITY_TYPE varchar(100) NOT NULL,
      ENTITY_ID int NOT NULL DEFAULT 0,
      EVENT_ID varchar(100) NOT NULL,
      HASH varchar(32),
      IS_HTML char(1) DEFAULT 'N',
      PRIMARY KEY (ID)
);

CREATE TABLE b_xdi_lf_scheme_right (
      SCHEME_ID int NOT NULL,
      GROUP_CODE varchar(100) NOT NULL
);
CREATE UNIQUE INDEX ux_b_xdi_lf_scheme_right_scheme_id_group_code ON b_xdi_lf_scheme_right (scheme_id, group_code);

CREATE TABLE b_xdi_user_right (
      USER_ID int NOT NULL,
      GROUP_CODE varchar(100) NOT NULL
);
CREATE UNIQUE INDEX ux_b_xdi_user_right_user_id_group_code ON b_xdi_user_right (user_id, group_code);