<?
if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();



class IntranetUstatDepartment extends \CBitrixComponent implements \Bitrix\Main\Engine\Contract\Controllerable
{
	public function executeComponent()
	{
		return parent::executeComponent(); // TODO: Change the autogenerated stub
	}

	public function configureActions()
	{
		$defaultPrefilters = [
			new \Bitrix\Intranet\ActionFilter\UserType(['employee']),
		];

		return [
			'getJson' => [
				'prefilters' => $defaultPrefilters
			]
		];
	}

	public function getJsonAction(): ?\Bitrix\Main\Engine\Response\AjaxJson
	{
		if (\Bitrix\Main\Engine\CurrentUser::get()->getId() > 0)
		{
			$this->executeComponent();
			return new \Bitrix\Main\Engine\Response\AjaxJson($this->arResult);
		}
		return null;
	}
}