/**
 * @module tasks/statemanager/redux/slices/flows/src/tool
 */
jn.define('tasks/statemanager/redux/slices/flows/src/tool', (require, exports, module) => {
	const prepareFlow = ({
		id,
		ownerId,
		creatorId,
		groupId,
		templateId,
		efficiency,
		active,
		demo,
		enableFlowUrl,
		plannedCompletionTime,
		plannedCompletionTimeText,
		averagePendingTime,
		averageAtWorkTime,
		averageCompletedTime,
		name,
		distributionType,
		taskCreators,
		taskAssignees,
		pending,
		atWork,
		completed,
		tasksTotal,
		myTasksTotal,
		myTasksCounter,
		activity,
		description,
		responsibleCanChangeDeadline,
		matchWorkTime,
		notifyAtHalfTime,
		notifyOnQueueOverflow,
		notifyOnTasksInProgressOverflow,
		notifyWhenEfficiencyDecreases,
		aiAdvice,
	}) => ({
		id: Number(id),
		ownerId,
		creatorId,
		groupId,
		templateId,
		efficiency,
		efficiencySuccess: Number(efficiency) >= 70,
		active,
		demo,
		enableFlowUrl,
		plannedCompletionTime,
		plannedCompletionTimeText,
		averagePendingTime,
		averageAtWorkTime,
		averageCompletedTime,
		name,
		distributionType,
		taskCreators,
		taskAssignees,
		pending,
		atWork,
		completed,
		tasksTotal,
		myTasksTotal,
		myTasksCounter,
		activity,
		description,
		responsibleCanChangeDeadline,
		matchWorkTime,
		notifyAtHalfTime,
		notifyOnQueueOverflow,
		notifyOnTasksInProgressOverflow,
		notifyWhenEfficiencyDecreases,
		aiAdvice,
	});

	module.exports = {
		prepareFlow,
	};
});
