<?php

return [
	'extensions' => [
		'apptheme',
		'asset-manager',
		'assets/common',
		'feature',
		'haptics',
		'layout/ui/context-menu',
		'layout/ui/loading-screen',
		'layout/ui/menu',
		'layout/ui/stateful-list',
		'layout/ui/search-bar',
		'ui-system/blocks/status-block',
		'loc',
		'notify',
		'rest',
		'rest/run-action-executor',
		'utils/object',
		'tasks:enum',
		'toast',
		'statemanager/redux/batched-actions',
		'statemanager/redux/slices/users',
		'statemanager/redux/store',
		'tasks:layout/action-menu',
		'tasks:layout/task/create/opener',
		'tasks:layout/online',
		'tasks:layout/flow/list/type',
		'tasks:flow-list',
		'tasks:flow-list/simple-list/items',
		'tasks:task/calendar',
		'tasks:statemanager/redux/slices/flows',
		'tasks:statemanager/redux/slices/groups',
		'tasks:statemanager/redux/slices/tasks',
		'tasks:statemanager/redux/types',
	],
];
