
CREATE TABLE b_imopenlines_session (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MODE varchar(255) DEFAULT 'input',
	STATUS smallint DEFAULT '0',
	SOURCE varchar(255),
	CONFIG_ID int,
	OPERATOR_ID int,
	OPERATOR_FROM_CRM char(1) NOT NULL DEFAULT 'N',
	USER_CODE varchar(255),
	PARENT_ID int DEFAULT 0,
	USER_ID int NOT NULL,
	CHAT_ID int NOT NULL,
	MESSAGE_COUNT int NOT NULL,
	LIKE_COUNT int,
	START_ID int NOT NULL,
	END_ID int NOT NULL,
	CRM char(1) NOT NULL DEFAULT 'N',
	CRM_CREATE char(1) NOT NULL DEFAULT 'N',
	CRM_CREATE_LEAD char(1) NOT NULL DEFAULT 'N',
	CRM_CREATE_COMPANY char(1) NOT NULL DEFAULT 'N',
	CRM_CREATE_CONTACT char(1) NOT NULL DEFAULT 'N',
	CRM_CREATE_DEAL char(1) NOT NULL DEFAULT 'N',
	CRM_ACTIVITY_ID int,
	CRM_TRACE_DATA text,
	DATE_CREATE timestamp,
	DATE_OPERATOR timestamp,
	DATE_MODIFY timestamp,
	DATE_OPERATOR_ANSWER timestamp,
	DATE_OPERATOR_CLOSE timestamp,
	DATE_FIRST_ANSWER timestamp,
	DATE_LAST_MESSAGE timestamp,
	DATE_FIRST_LAST_USER_ACTION timestamp,
	DATE_CLOSE timestamp,
	DATE_CLOSE_VOTE timestamp,
	TIME_FIRST_ANSWER int,
	TIME_ANSWER int,
	TIME_CLOSE int,
	TIME_BOT int,
	TIME_DIALOG int,
	CATEGORY_ID int DEFAULT 0,
	WAIT_ACTION char(1) NOT NULL DEFAULT 'N',
	WAIT_ANSWER char(1) NOT NULL DEFAULT 'Y',
	WAIT_VOTE char(1) NOT NULL DEFAULT 'N',
	SEND_FORM varchar(255) DEFAULT 'none',
	SEND_HISTORY char(1) NOT NULL DEFAULT 'N',
	CLOSED char(1) NOT NULL DEFAULT 'N',
	PAUSE char(1) NOT NULL DEFAULT 'N',
	SPAM char(1) NOT NULL DEFAULT 'N',
	WORKTIME char(1) NOT NULL DEFAULT 'Y',
	SEND_NO_ANSWER_TEXT char(1) NOT NULL DEFAULT 'N',
	SEND_NO_WORK_TIME_TEXT char(1) NOT NULL DEFAULT 'N',
	QUEUE_HISTORY text,
	BLOCK_REASON varchar(255),
	BLOCK_DATE timestamp,
	VOTE int,
	VOTE_HEAD int,
	COMMENT_HEAD text,
	EXTRA_REGISTER int,
	EXTRA_TARIFF varchar(255),
	EXTRA_USER_LEVEL varchar(255),
	EXTRA_PORTAL_TYPE varchar(255),
	EXTRA_URL varchar(255),
	IS_FIRST char(1) NOT NULL,
	LAST_SEND_MAIL_ID int NOT NULL DEFAULT 0,
	USER_LANG varchar(5),
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_session_user_code_closed ON b_imopenlines_session (user_code, closed);
CREATE INDEX ix_b_imopenlines_session_user_id_closed ON b_imopenlines_session (user_id, closed);
CREATE INDEX ix_b_imopenlines_session_chat_id_closed ON b_imopenlines_session (chat_id, closed);
CREATE INDEX ix_b_imopenlines_session_operator_id_closed_date_create ON b_imopenlines_session (operator_id, closed, date_create);
CREATE INDEX ix_b_imopenlines_session_operator_id_closed_date_modify ON b_imopenlines_session (operator_id, closed, date_modify);
CREATE INDEX ix_b_imopenlines_session_extra_url_date_create ON b_imopenlines_session (extra_url, date_create);
CREATE INDEX ix_b_imopenlines_session_extra_tariff_date_create ON b_imopenlines_session (extra_tariff, date_create);
CREATE INDEX ix_b_imopenlines_session_vote_vote_head_date_create ON b_imopenlines_session (vote, vote_head, date_create);
CREATE INDEX ix_b_imopenlines_session_spam_date_create ON b_imopenlines_session (spam, date_create);
CREATE INDEX ix_b_imopenlines_session_status_date_create ON b_imopenlines_session (status, date_create);
CREATE INDEX ix_b_imopenlines_session_date_create ON b_imopenlines_session (date_create);
CREATE INDEX ix_b_imopenlines_session_config_id ON b_imopenlines_session (config_id);
CREATE INDEX ix_b_imopenlines_session_status_date_close ON b_imopenlines_session (status, date_close);
CREATE INDEX ix_b_imopenlines_session_operator_id_date_create ON b_imopenlines_session (operator_id, date_create);
CREATE INDEX ix_b_imopenlines_session_operator_config_status ON b_imopenlines_session (operator_id, config_id, status);

CREATE TABLE b_imopenlines_session_index (
	SESSION_ID int NOT NULL,
	SEARCH_CONTENT text,
	PRIMARY KEY (SESSION_ID)
);

CREATE TABLE b_imopenlines_user_relation (
	USER_CODE varchar(255) NOT NULL,
	USER_ID int DEFAULT 0,
	CHAT_ID int DEFAULT 0,
	AGREES char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (USER_CODE)
);

CREATE TABLE b_imopenlines_session_check (
	SESSION_ID int NOT NULL,
	DATE_CLOSE timestamp,
	DATE_QUEUE timestamp,
	DATE_MAIL timestamp,
	DATE_NO_ANSWER timestamp,
	UNDISTRIBUTED char(1) NOT NULL,
	REASON_RETURN varchar(255) NOT NULL,
	PRIMARY KEY (SESSION_ID)
);
CREATE INDEX ix_b_imopenlines_session_check_date_close ON b_imopenlines_session_check (date_close);
CREATE INDEX ix_b_imopenlines_session_check_date_queue ON b_imopenlines_session_check (date_queue);
CREATE INDEX ix_b_imopenlines_session_check_date_mail ON b_imopenlines_session_check (date_mail);
CREATE INDEX ix_b_imopenlines_session_check_undistributed ON b_imopenlines_session_check (undistributed);

CREATE TABLE b_imopenlines_session_automatic_tasks (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CONFIG_AUTOMATIC_MESSAGE_ID int NOT NULL,
	SESSION_ID int NOT NULL,
	DATE_TASK timestamp NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE b_imopenlines_livechat (
	CONFIG_ID int NOT NULL,
	URL_CODE varchar(255),
	URL_CODE_ID int,
	URL_CODE_PUBLIC varchar(255),
	URL_CODE_PUBLIC_ID int,
	TEMPLATE_ID varchar(255) DEFAULT NULL,
	BACKGROUND_IMAGE int DEFAULT NULL,
	CSS_ACTIVE char(1) NOT NULL DEFAULT 'N',
	CSS_PATH varchar(255) DEFAULT NULL,
	CSS_TEXT text,
	COPYRIGHT_REMOVED char(1) NOT NULL DEFAULT 'N',
	CACHE_WIDGET_ID int,
	CACHE_BUTTON_ID int,
	PHONE_CODE varchar(255),
	TEXT_PHRASES text,
	SHOW_SESSION_ID char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (CONFIG_ID)
);

CREATE TABLE b_imopenlines_config (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	XML_ID varchar(255),
	ACTIVE char(1) NOT NULL DEFAULT 'N',
	LINE_NAME varchar(255),
	CRM char(1) NOT NULL DEFAULT 'Y',
	CRM_CREATE varchar(50) DEFAULT 'none',
	CRM_CREATE_SECOND varchar(50) DEFAULT '',
	CRM_CREATE_THIRD varchar(50) DEFAULT '',
	CRM_FORWARD char(1) NOT NULL DEFAULT 'Y',
	CRM_CHAT_TRACKER char(1) NOT NULL DEFAULT 'Y',
	CRM_SOURCE varchar(50) DEFAULT 'create',
	CRM_TRANSFER_CHANGE char(1) NOT NULL DEFAULT 'Y',
	QUEUE_TIME int DEFAULT 60,
	NO_ANSWER_TIME int DEFAULT 60,
	QUEUE_TYPE varchar(50) DEFAULT 'evenly',
	CHECK_AVAILABLE char(1) NOT NULL DEFAULT 'N',
	WATCH_TYPING char(1) NOT NULL DEFAULT 'N',
	WELCOME_MESSAGE char(1) NOT NULL DEFAULT 'Y',
	WELCOME_MESSAGE_TEXT text,
	WELCOME_BOT_ENABLE char(1) DEFAULT 'N',
	WELCOME_BOT_JOIN varchar(50) DEFAULT 'first',
	WELCOME_BOT_ID int DEFAULT 0,
	WELCOME_BOT_TIME int DEFAULT 60,
	WELCOME_BOT_LEFT varchar(50) DEFAULT 'queue',
	AGREEMENT_MESSAGE char(1) NOT NULL DEFAULT 'N',
	AGREEMENT_ID int DEFAULT 0,
	NO_ANSWER_RULE varchar(50) DEFAULT 'none',
	NO_ANSWER_FORM_ID int,
	NO_ANSWER_BOT_ID int,
	NO_ANSWER_TEXT text,
	WORKTIME_ENABLE char(1) DEFAULT 'N',
	WORKTIME_FROM varchar(5),
	WORKTIME_TO varchar(5),
	WORKTIME_TIMEZONE varchar(50),
	WORKTIME_HOLIDAYS text,
	WORKTIME_DAYOFF varchar(20),
	WORKTIME_DAYOFF_RULE varchar(50) DEFAULT 'form',
	WORKTIME_DAYOFF_FORM_ID int,
	WORKTIME_DAYOFF_BOT_ID int,
	WORKTIME_DAYOFF_TEXT text,
	CATEGORY_ENABLE char(1) DEFAULT 'N',
	CATEGORY_ID int DEFAULT 0,
	CLOSE_RULE varchar(50) DEFAULT 'form',
	CLOSE_FORM_ID int,
	CLOSE_BOT_ID int,
	CLOSE_TEXT text,
	FULL_CLOSE_TIME int DEFAULT 10,
	AUTO_CLOSE_RULE varchar(50) DEFAULT 'none',
	AUTO_CLOSE_FORM_ID int,
	AUTO_CLOSE_BOT_ID int,
	AUTO_CLOSE_TIME int DEFAULT 0,
	AUTO_CLOSE_TEXT text,
	AUTO_EXPIRE_TIME int DEFAULT 0,
	VOTE_MESSAGE char(1) NOT NULL DEFAULT 'Y',
	VOTE_TIME_LIMIT int DEFAULT 0,
	VOTE_BEFORE_FINISH char(1) NOT NULL DEFAULT 'Y',
	VOTE_CLOSING_DELAY char(1) NOT NULL DEFAULT 'N',
	VOTE_MESSAGE_1_TEXT text,
	VOTE_MESSAGE_1_LIKE text,
	VOTE_MESSAGE_1_DISLIKE text,
	VOTE_MESSAGE_2_TEXT text,
	VOTE_MESSAGE_2_LIKE text,
	VOTE_MESSAGE_2_DISLIKE text,
	DATE_CREATE timestamp,
	DATE_MODIFY timestamp,
	MODIFY_USER_ID int,
	TEMPORARY char(1) NOT NULL DEFAULT 'Y',
	QUICK_ANSWERS_IBLOCK_ID int DEFAULT 0,
	SESSION_PRIORITY int DEFAULT 0,
	LANGUAGE_ID char(2),
	TYPE_MAX_CHAT varchar(255),
	MAX_CHAT int,
	OPERATOR_DATA varchar(50) NOT NULL DEFAULT 'profile',
	DEFAULT_OPERATOR_DATA text,
	KPI_FIRST_ANSWER_TIME int DEFAULT 0,
	KPI_FIRST_ANSWER_ALERT char(1) NOT NULL DEFAULT 'N',
	KPI_FIRST_ANSWER_LIST text,
	KPI_FIRST_ANSWER_TEXT text,
	KPI_FURTHER_ANSWER_TIME int DEFAULT 0,
	KPI_FURTHER_ANSWER_ALERT char(1) NOT NULL DEFAULT 'N',
	KPI_FURTHER_ANSWER_LIST text,
	KPI_FURTHER_ANSWER_TEXT text,
	KPI_CHECK_OPERATOR_ACTIVITY char(1) NOT NULL DEFAULT 'N',
	SEND_NOTIFICATION_EMPTY_QUEUE char(1) NOT NULL DEFAULT 'N',
	USE_WELCOME_FORM char(1) NOT NULL DEFAULT 'Y',
	WELCOME_FORM_ID int DEFAULT NULL,
	WELCOME_FORM_DELAY char(1) DEFAULT 'Y',
	SEND_WELCOME_EACH_SESSION char(1) NOT NULL DEFAULT 'N',
	CONFIRM_CLOSE char(1) NOT NULL DEFAULT 'N',
	IGNORE_WELCOME_FORM_RESPONSIBLE char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID)
);

CREATE TABLE b_imopenlines_config_automatic_messages (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ACTIVE char(1) NOT NULL DEFAULT 'Y',
	CONFIG_ID int NOT NULL,
	TIME_TASK int NOT NULL,
	MESSAGE text,
	TEXT_BUTTON_CLOSE varchar(255),
	LONG_TEXT_BUTTON_CLOSE varchar(255),
	AUTOMATIC_TEXT_CLOSE text,
	TEXT_BUTTON_CONTINUE varchar(255),
	LONG_TEXT_BUTTON_CONTINUE varchar(255),
	AUTOMATIC_TEXT_CONTINUE text,
	TEXT_BUTTON_NEW varchar(255),
	LONG_TEXT_BUTTON_NEW varchar(255),
	AUTOMATIC_TEXT_NEW text,
	PRIMARY KEY (ID)
);

CREATE TABLE b_imopenlines_config_statistic (
	CONFIG_ID int NOT NULL,
	SESSION int,
	MESSAGE int,
	CLOSED int,
	IN_WORK int,
	LEAD int,
	PRIMARY KEY (CONFIG_ID)
);

CREATE TABLE b_imopenlines_config_category (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CONFIG_ID int NOT NULL,
	CODE varchar(50),
	VALUE varchar(255),
	SORT int NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_config_category_code ON b_imopenlines_config_category (code);
CREATE INDEX ix_b_imopenlines_config_category_config_id_sort ON b_imopenlines_config_category (config_id, sort);

CREATE TABLE b_imopenlines_config_queue (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SORT int DEFAULT 0,
	CONFIG_ID int NOT NULL,
	ENTITY_ID int NOT NULL,
	ENTITY_TYPE varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_config_queue_config_id ON b_imopenlines_config_queue (config_id);
CREATE INDEX ix_b_imopenlines_config_queue_entity_id_entity_type ON b_imopenlines_config_queue (entity_id, entity_type);

CREATE TABLE b_imopenlines_queue (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SORT int DEFAULT 0,
	CONFIG_ID int NOT NULL,
	USER_ID int NOT NULL,
	DEPARTMENT_ID int DEFAULT 0,
	LAST_ACTIVITY_DATE timestamp,
	LAST_ACTIVITY_DATE_EXACT int8,
	USER_NAME varchar(255),
	USER_WORK_POSITION varchar(255),
	USER_AVATAR text,
	USER_AVATAR_ID int DEFAULT 0,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_queue_config_id_last_activity_date ON b_imopenlines_queue (config_id, last_activity_date);
CREATE INDEX ix_b_imopenlines_queue_user_id ON b_imopenlines_queue (user_id);

CREATE TABLE b_imopenlines_operator_transfer (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CONFIG_ID int NOT NULL,
	SESSION_ID int NOT NULL,
	USER_ID int NOT NULL,
	TRANSFER_MODE varchar(50) DEFAULT 'MANUAL',
	TRANSFER_TYPE varchar(50) DEFAULT 'USER',
	TRANSFER_USER_ID int,
	TRANSFER_LINE_ID int,
	DATE_CREATE timestamp,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_operator_transfer_config_id ON b_imopenlines_operator_transfer (config_id);
CREATE INDEX ix_b_imopenlines_operator_transfer_session_id ON b_imopenlines_operator_transfer (session_id);
CREATE INDEX ix_b_imopenlines_operator_transfer_date_create ON b_imopenlines_operator_transfer (date_create);
CREATE INDEX ix_b_imopenlines_operator_transfer_user_id_config_id ON b_imopenlines_operator_transfer (user_id, config_id);

CREATE TABLE b_imopenlines_tracker (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SESSION_ID int,
	CHAT_ID int,
	MESSAGE_ID int,
	MESSAGE_ORIGIN_ID int,
	USER_ID int,
	TRACK_ID varchar(50),
	ACTION varchar(50),
	CRM_ENTITY_TYPE varchar(50),
	CRM_ENTITY_ID int,
	CRM_CONTACT_ID int,
	CRM_COMPANY_ID int,
	CRM_DEAL_ID int,
	CRM_LEAD_ID int,
	FIELD_ID varchar(255) DEFAULT 'FM',
	FIELD_TYPE varchar(255),
	FIELD_VALUE varchar(255),
	DATE_CREATE timestamp,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_tracker_message_id ON b_imopenlines_tracker (message_id);
CREATE INDEX ix_b_imopenlines_tracker_crm_deal_id_action_date_create ON b_imopenlines_tracker(crm_deal_id, action, date_create);

CREATE TABLE b_imopenlines_role (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	NAME varchar(255) NOT NULL,
	XML_ID varchar(255),
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_role_xml_id ON b_imopenlines_role (xml_id);

CREATE TABLE b_imopenlines_role_permission (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ROLE_ID int NOT NULL,
	ENTITY varchar(50) NOT NULL,
	ACTION varchar(50) NOT NULL,
	PERMISSION char(1),
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_role_permission_role_id ON b_imopenlines_role_permission (role_id);

CREATE TABLE b_imopenlines_role_access (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ROLE_ID int NOT NULL,
	ACCESS_CODE varchar(100) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_role_access_role_id ON b_imopenlines_role_access (role_id);

CREATE TABLE b_imopenlines_rest_network_limit (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOT_ID int NOT NULL,
	USER_ID int NOT NULL,
	DATE_CREATE timestamp,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_rest_network_limit_bot_id_date_create ON b_imopenlines_rest_network_limit (bot_id, date_create);

CREATE TABLE b_imopenlines_dialog_stat (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	DATE timestamp NOT NULL,
	OPEN_LINE_ID int NOT NULL,
	SOURCE_ID varchar(255) NOT NULL,
	OPERATOR_ID int NOT NULL,
	FIRST_TREATMENT_QTY int NOT NULL DEFAULT 0,
	REPEATED_TREATMENT_QTY int NOT NULL DEFAULT 0,
	POSITIVE_QTY int NOT NULL DEFAULT 0,
	NEGATIVE_QTY int NOT NULL DEFAULT 0,
	WITHOUT_MARK_QTY int NOT NULL DEFAULT 0,
	ANSWERED_QTY int NOT NULL DEFAULT 0,
	SKIP_QTY int NOT NULL DEFAULT 0,
	APPOINTED_QTY int NOT NULL DEFAULT 0,
	AVERAGE_SECS_TO_ANSWER int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_imopenlines_dialog_stat_date_open_line_id_source_id_operat ON b_imopenlines_dialog_stat (date, open_line_id, source_id, operator_id);

CREATE TABLE b_imopenlines_statistic_queue (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SESSION_ID int NOT NULL,
	STATISTIC_KEY varchar(255) NOT NULL,
	DATE_QUEUE timestamp NOT NULL,
	PARAMS text NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_imopenlines_statistic_queue_date_queue ON b_imopenlines_statistic_queue (date_queue);

CREATE TABLE b_imopenlines_treatment_by_hour_stat (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	DATE timestamp NOT NULL,
	OPEN_LINE_ID int NOT NULL,
	SOURCE_ID varchar(255) NOT NULL,
	OPERATOR_ID int NOT NULL,
	QTY int NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_imopenlines_treatment_by_hour_stat_date_open_line_id_sourc ON b_imopenlines_treatment_by_hour_stat (date, open_line_id, source_id, operator_id);

CREATE TABLE b_imopenlines_log (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	DATA_TIME timestamp,
	LINE_ID varchar(255),
	CONNECTOR_ID varchar(255),
	SESSION_ID int,
	TYPE varchar(255),
	DATA text,
	TRACE text
);

CREATE TABLE b_imopenlines_exec_log (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	EXEC_FUNCTION varchar(255) NOT NULL,
	LAST_EXEC_TIME timestamp NOT NULL,
	IS_SUCCESS char(1) NOT NULL DEFAULT 'Y'
);

CREATE TABLE b_imopenlines_session_kpi_messages (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SESSION_ID int NOT NULL,
	MESSAGE_ID int NOT NULL,
	IS_FIRST_MESSAGE char(1) NOT NULL DEFAULT 'Y',
	TIME_RECEIVED timestamp NOT NULL,
	TIME_ANSWER timestamp,
	TIME_EXPIRED timestamp,
	TIME_STOP timestamp,
	TIME_STOP_HISTORY text,
	IS_SENT_EXPIRED_NOTIFICATION char(1) NOT NULL DEFAULT 'N'
);
CREATE INDEX ix_b_imopenlines_session_kpi_messages_session_id ON b_imopenlines_session_kpi_messages (session_id);
CREATE INDEX ix_b_imopenlines_session_kpi_messages_is_sent_expired_notificat ON b_imopenlines_session_kpi_messages (is_sent_expired_notification, time_answer, time_stop, time_expired);

CREATE TABLE b_imopenlines_lock (
	ID varchar(255) NOT NULL,
	DATE_CREATE timestamp NOT NULL,
	LOCK_TIME timestamp NOT NULL,
	PID varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_imopenlines_lock_id ON b_imopenlines_lock (id);

CREATE TABLE b_imopenlines_event_log (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	LINE_ID int NOT NULL,
	EVENT_TYPE varchar(255) NOT NULL,
	DATE_TIME timestamp NOT NULL,
	IS_ERROR char(1) NOT NULL DEFAULT 'N',
	EVENT_MESSAGE text,
	SESSION_ID int,
	MESSAGE_ID int,
	ADDITIONAL_FIELDS text
);

CREATE TABLE b_imopenlines_chat_index (
	CHAT_ID int NOT NULL,
	SEARCH_TITLE varchar(511),
	PRIMARY KEY (CHAT_ID)
);

CREATE TABLE b_imopenlines_user_option (
	USER_ID int NOT NULL,
	PAUSE char(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (USER_ID)
);
CREATE INDEX ix_b_imopenlines_user_option_pause ON b_imopenlines_user_option (pause);

CREATE TABLE b_imopenlines_user_log (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL,
	TYPE varchar(255) NOT NULL,
	DATA text NOT NULL,
	DATE_CREATE timestamp NOT NULL
);
CREATE INDEX ix_b_imopenlines_user_log_user_id_type_date_create ON b_imopenlines_user_log (user_id, type, date_create);

CREATE TABLE b_imopenlines_recent (
	USER_ID int NOT NULL,
	CHAT_ID int NOT NULL,
	MESSAGE_ID int NOT NULL,
	SESSION_ID int NOT NULL,
	DATE_CREATE timestamp NOT NULL,
	PRIMARY KEY (USER_ID, CHAT_ID)
);
