<?php

return [
	'extensions' => [
		'tokens',
		'rest',
		'loc',
		'error',
		'alert',
		'assets/icons',
		'utils/object',
		'utils/string',
		'utils/type',
		'notify-manager',
		'ui-system/layout/box',
		'ui-system/layout/area-list',
		'ui-system/layout/area',
		'ui-system/typography/heading',
		'ui-system/typography/text',
		'ui-system/form/inputs/string',
		'ui-system/form/inputs/textarea',
		'selector/widget/factory',
		'ui-system/form/buttons',
		'layout/ui/setting-selector-list',
		'layout/ui/menu',
		'avatar-picker',
		'collab/invite',
		'type',
		'haptics',
		'im:messenger/api/dialog-opener',
	],
    'bundle' => [
		'./src/intro',
		'./src/permissions',
		'./src/edit',
		'./src/security',
		'./src/image',
		'./src/settings-banner',
	],
];
