<?php
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT1"] = "You're a real pro! You now have more than #COUNT# companies in your Bitrix24. Please note: you will be able to search companies only on the commercial plans when their number exceeds #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_COMPANY_WARNING_TEXT2"] = "Searching so many companies will require considerable resources, thus only the preset filters can be used on the Free plan. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT1"] = "You're a real pro! You now have more than #COUNT# contacts in your Bitrix24. Please note: you will be able to search contacts only on the commercial plans when their number exceeds #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_CONTACT_WARNING_TEXT2"] = "Searching so many contacts will require considerable resources, thus only the preset filters can be used on the Free plan. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT1"] = "You're a real pro! You now have more than #COUNT# deals in your Bitrix24. Please note: you will be able to search deals only on the commercial plans when their number exceeds #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_DEAL_WARNING_TEXT2"] = "Searching so many deals will require considerable resources, thus only the preset filters can be used on the Free plan. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_COMPANY_CONTENT"] = "Company search limit (#LIMIT#) reached. We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTACT_CONTENT"] = "Contact search limit (#LIMIT#) reached. We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_CONTENT2"] = "The larger the scale of your business, the more data to search you create. Choose a plan that fits your data to search faster.  #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DEAL_CONTENT"] = "Deal search limit (#LIMIT#) reached. We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_DYNAMIC_CONTENT"] = "Your Smart Process Automation has more than #LIMIT# items. Please upgrade to one of the major plans to search more items.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_INVOICE_CONTENT"] = "Invoice search limit (#LIMIT#) reached. We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_LEAD_CONTENT"] = "Lead search limit (#LIMIT#) reached. We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_ORDER_CONTENT"] = "Order search limit (#LIMIT#) reached. We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_QUOTE_CONTENT"] = "Quote search limit (#LIMIT#) reached. We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_FILTER_TITLE"] = "Maximum search limit reached";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_HELPDESK_LINK"] = "Details";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT1"] = "You're a real pro! You now have more than #COUNT# invoices in your Bitrix24. Please note: you will be able to search invoices only on the commercial plans when their number exceeds #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_INVOICE_WARNING_TEXT2"] = "Searching so many invoices will require considerable resources, thus only the preset filters can be used on the Free plan. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT1"] = "You're a real pro! You now have more than #COUNT# leads in your Bitrix24. Please note: you will be able to search leads only on the commercial plans when their number exceeds #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LEAD_WARNING_TEXT2"] = "Searching so many leads will require considerable resources, thus only the preset filters can be used on the Free plan. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_LIMIT_CONTENT"] = "
	<p>We are striving to improve service quality and performance to fit your business scale. The amount of data increases as your business grows: new tasks, deals and other entities are created every day.</p>
	<p>The larger the scale of your business, the more data to search you create. Choose a plan that fits your data to search faster.</p>
";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT1"] = "You're a real pro! You now have more than #COUNT# orders in your Bitrix24. Please note: you will be able to search orders only on the commercial plans when their number exceeds #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_ORDER_WARNING_TEXT2"] = "Searching so many orders will require considerable resources, thus only the preset filters can be used on the Free plan. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT1"] = "You're a real pro! You now have more than #COUNT# quotes in your Bitrix24. Please note: you will be able to search quotes only on the commercial plans when their number exceeds #LIMIT#.";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_QUOTE_WARNING_TEXT2"] = "Searching so many quotes will require considerable resources, thus only the preset filters can be used on the Free plan. #HELPDESK_LINK#";
$MESS["CRM_B24_SEARCH_LIMIT_RESTRICTION_TITLE"] = "Item limit (#LIMIT#) reached";
