<?php

return [
	'extensions' => [
		'feature',
		'type',
		'loc',
		'in-app-url',
		'notify-manager',
		'assets/common',
		'assets/icons',
		'layout/ui/menu',
		'layout/ui/friendly-date',
		'layout/ui/floating-button',
		'layout/ui/copilot-role-selector',
		'layout/ui/file/icon',
		'utils/object',
		'utils/date',
		'utils/file',
		'utils/date/formats',
		'utils/url',
		'utils/color',
		'tokens',
		'ui-system/layout/card',
		'ui-system/blocks/badges/counter',
		'ui-system/blocks/badges/counter/src/design-enum',
		'selector/widget/entity/socialnetwork/user',

		'im:lib/theme',
		'im:messenger/const',
		'im:messenger/assets/common',

		'im:messenger/controller/chat-composer',
		'im:messenger/controller/user-profile',
		'im:messenger/controller/user-add',
		'im:messenger/controller/participant-manager',
		'im:messenger/controller/dialog/lib/helper/text',

		'im:messenger/lib/params',
		'im:messenger/lib/feature',
		'im:messenger/lib/rest',
		'im:messenger/lib/element',
		'im:messenger/lib/logger',
		'im:messenger/lib/helper',
		'im:messenger/lib/utils',
		'im:messenger/lib/plan-limit',
		'im:messenger/lib/permission-manager',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/ui/base/item',
		'im:messenger/lib/ui/base/avatar',
		'im:messenger/lib/ui/base/loader',
		'im:messenger/lib/ui/base/buttons',
		'im:messenger/lib/ui/notification',
		'im:messenger/lib/ui/alert',

		'im:messenger/provider/rest',
		'im:messenger/provider/data',
		'im:messenger/provider/service',
	],
	'bundle' => [
		'./lib/assets/icons',
		'./lib/const',
		
		'./src/base/sidebar-controller',
		
		'./src/chat/sidebar-controller',
		'./src/chat/sidebar-view',
		'./src/chat/sidebar-friendly-date',
		'./src/chat/sidebar-service',
		'./src/chat/sidebar-profile-btn',
		'./src/chat/sidebar-profile-user-counter',
		'./src/chat/sidebar-profile-info',
		'./src/chat/sidebar-user-service',
		'./src/chat/sidebar-rest-service',
		'./src/chat/sidebar-plan-limit-banner',
		'./src/chat/tabs/tab-view',
		'./src/chat/tabs/base/view',
		'./src/chat/tabs/participants/participants-view',
		'./src/chat/tabs/participants/participants-service',
		'./src/chat/tabs/files/view',
		'./src/chat/tabs/files/item',
		'./src/chat/tabs/files/service',
		'./src/chat/tabs/files/context-menu',

		'./src/chat/tabs/links/view',
		'./src/chat/tabs/links/item',
		'./src/chat/tabs/links/service',
		'./src/chat/tabs/links/context-menu',

		'./src/channel/sidebar-controller',
		'./src/channel/sidebar-view',
		'./src/channel/profile-user-counter-view',
		'./src/channel/profile-info',
		'./src/channel/profile-btn-view',
		'./src/channel/tabs/tab-view',
		'./src/channel/tabs/participants/participants-view',
		'./src/channel/tabs/participants/participants-service',

		'./src/comment/sidebar-controller',
		'./src/comment/sidebar-view',
		'./src/comment/profile-info',

		'./src/collab/sidebar-view',
		'./src/collab/profile-info',
		'./src/collab/sidebar-controller',
		'./src/collab/profile-buttons-controller',
		'./src/collab/profile-button-view',
		'./src/collab/tabs/participants/participants-view',
		'./src/collab/tabs/tab-view',
		'./src/collab/header-top-menu',
	],
];
