<?php

return [
	'extensions' => [
		'type',
		'loc',
		'utils/object',
		'utils/date',
		'utils/date/formats',
		'assets/common',
		'layout/ui/friendly-date',
		'layout/ui/floating-button',
		'im:messenger/core',
		'im:messenger/const',
		'im:messenger/provider/rest',
		'im:messenger/assets/common',
		'im:messenger/lib/params',
		'im:messenger/lib/rest',
		'im:messenger/lib/ui/base/buttons',
		'im:messenger/lib/element',
		'im:messenger/lib/logger',
		'im:messenger/controller/user-profile',
		'im:messenger/lib/ui/base/item',
		'im:messenger/lib/ui/base/avatar',
		'im:messenger/lib/ui/base/loader',
		'im:messenger/lib/utils',
		'im:messenger/lib/permission-manager',
        'im:messenger/controller/user-profile',
		'im/messenger/controller/user-add',
		'im:messenger/controller/participant-manager',
	],
	'bundle' => [
		'./src/sidebar-controller',
		'./src/sidebar-services',
		'./src/tab-view',
		'./src/participants-view',
		'./src/sidebar-view',
		'./src/sidebar-friendly-date',
	],
];