<?php
$MESS["SBLP_Q_DE_COLUMN_NUMBER_VALUE"] = "Pos.";
$MESS["SBLP_Q_DE_COLUMN_NAME_VALUE"] = "Leistung";
$MESS["SBLP_Q_DE_COLUMN_QUANTITY_VALUE"] = "Anzahl";
$MESS["SBLP_Q_DE_COLUMN_DISCOUNT_VALUE"] = "Rabatt";
$MESS["SBLP_Q_DE_COLUMN_VAT_RATE_VALUE"] = "MwSt.";
$MESS["SBLP_Q_DE_COLUMN_SUM_VALUE"] = "Gesamtpreis";
$MESS["SBLP_Q_DE_COLUMN_PRICE_VALUE"] = "Einzelpreis";
$MESS["SBLP_Q_DE_COLUMN_MEASURE_VALUE"] = "Einheit";
