<?
$DB->Query("DELETE FROM b_event_type WHERE EVENT_NAME in (
	'TASK_REMINDER',
	'TASKS_ADD_TASK',
	'TASKS_UPDATE_TASK',
	'TASKS_STATUS_TASK',
	'TASKS_ADD_COMMENT',
	'TASKS_TASK_ADD_EMAIL',
	'TASKS_TASK_UPDATE_EMAIL',
	'TASKS_TASK_COMMENT_ADD_EMAIL'
)");

$DB->Query("DELETE FROM b_event_message WHERE EVENT_NAME in (
	'TASK_REMINDER',
	'TASKS_ADD_TASK',
	'TASKS_UPDATE_TASK',
	'TASKS_STATUS_TASK',
	'TASKS_ADD_COMMENT',
	'TASKS_TASK_ADD_EMAIL',
	'TASKS_TASK_UPDATE_EMAIL',
	'TASKS_TASK_COMMENT_ADD_EMAIL'
)");
?>