CREATE TABLE b_xdi_lf_scheme
(
	ID int(11)	NOT NULL auto_increment,
	LID CHAR(2) NOT NULL REFERENCES b_lang (LID),
	TYPE VARCHAR(100) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SORT int(11) DEFAULT 100 NOT NULL,
	ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
	AUTO CHAR(1) DEFAULT 'N' NOT NULL,	
	ENABLE_COMMENTS CHAR(1) DEFAULT 'Y',
	DAYS_OF_MONTH VARCHAR(100)	NULL,
	DAYS_OF_WEEK VARCHAR(15)	NULL,
	TIMES_OF_DAY VARCHAR(255)	NULL,
	LAST_EXECUTED datetime	NULL,
	HOST VARCHAR(255) NULL,	
	PORT VARCHAR(5) NULL,	
	PAGE VARCHAR(255) NULL,
	URI TEXT NULL,
	METHOD VARCHAR(255) NULL,
	PARAMS VARCHAR(255) NULL,
	LOGIN VARCHAR(255) NULL,
	PASSWORD VARCHAR(255) NULL,
	ENTITY_TYPE VARCHAR(100) NOT NULL,
	ENTITY_ID int(11) default 0 NOT NULL,	
	EVENT_ID VARCHAR(100) NOT NULL,
	HASH VARCHAR(32) NULL,
	IS_HTML CHAR(1) DEFAULT 'N',
	PRIMARY KEY (ID)
);

CREATE TABLE b_xdi_lf_scheme_right
(
	SCHEME_ID INT(11) NOT NULL,
	GROUP_CODE VARCHAR(100) NOT NULL,
	UNIQUE UX_B_LF_SCHEME_RIGHT (SCHEME_ID, GROUP_CODE)
);

CREATE TABLE b_xdi_user_right
(
	USER_ID INT(11) NOT NULL,
	GROUP_CODE VARCHAR(100) NOT NULL,
	UNIQUE UX_B_XDI_USER_RIGHT (USER_ID, GROUP_CODE)
);
