<?php

return [
	'extensions' => [
		'bottom-sheet',
		'loc',
		'haptics',
		'alert',
		'tokens',
		'type',
		'toast',
		'text-editor',
		'notify-manager',
		'layout/ui/scroll-view',
		'layout/ui/user/user-name',
		'layout/ui/fields/file/theme/air',
		'selector/widget/factory',
		'tariff-plan-restriction',
		'utils/object',
		'utils/color',
		'utils/date',
		'utils/skeleton',
		'ui-system/layout/box',
		'ui-system/layout/area',
		'ui-system/layout/card',
		'ui-system/form/buttons/button',
		'ui-system/form/inputs/input',
		'ui-system/form/inputs/string',
		'ui-system/blocks/link',
		'ui-system/typography/text',
		'ui-system/layout/dialog-footer',
		'ui-system/blocks/icon',
		'ui-system/blocks/avatar',
		'ui-system/popups/color-picker',
		'ui-system/blocks/status-block',

		'statemanager/redux/slices/users',
		'statemanager/redux/store',

		'calendar:ajax',
		'calendar:data-managers/user-manager',
		'calendar:data-managers/section-manager',
		'calendar:data-managers/location-manager',
		'calendar:data-managers/settings-manager',
		'calendar:date-helper',
		'calendar:state',
		'calendar:model/event',
		'calendar:enums',
		'calendar:statemanager/redux/slices/events',
		'calendar:base-menu',
	],
	'bundle' => [
		'./src/data-managers/accessibility-manager',
		'./src/data-managers/slots-calculator',
		'./src/data-managers/location-accessibility-manager',

		'./src/state',

		'./src/pages/about-page',
		'./src/pages/date-time-page',

		'./src/layout/event-name-input',
		'./src/layout/event-settings',
		'./src/layout/attendees-selector',
		'./src/layout/select-date-time-button',
		'./src/layout/month-selector',
		'./src/layout/slot-size-selector',
		'./src/layout/slot-list',
		'./src/layout/slot-item',
		'./src/layout/slot-list-skeleton',
		'./src/layout/slot-list-empty-state',
		'./src/layout/slot-calendar',
		'./src/layout/reminder-selector',
		'./src/layout/save-event-button',
		'./src/layout/save-event-container',
		'./src/layout/location-input',
		'./src/layout/section-info',
		'./src/layout/location-info',
		'./src/layout/description',

		'./src/selector/selector',
		'./src/selector/item',

		'./src/menu/reminder',
		'./src/menu/slot-size',
		'./src/menu/accessibility',
		'./src/menu/importance',
		'./src/menu/boolean',
	],
];
