<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
IncludeModuleLangFile($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/intranet/public_bitrix24/extranet/workgroups/index.php");
$APPLICATION->SetTitle(GetMessage("TITLE"));
?>
<?
GetGlobalID();
$componentDateTimeFormat = CIntranetUtils::getCurrentDateTimeFormat();

$APPLICATION->IncludeComponent("bitrix:socialnetwork_group", "", array(
	"ITEM_DETAIL_COUNT" => "32",
	"ITEM_MAIN_COUNT" => "6",
	"DATE_TIME_FORMAT" => $componentDateTimeFormat,
	"NAME_TEMPLATE" => "",
	"PATH_TO_USER" => "/extranet/contacts/personal/user/#user_id#/",
	"PATH_TO_USER_LOG" => "/extranet/contacts/personal/log/",
	"PATH_TO_SUBSCRIBE" => "/extranet/contacts/personal/subscribe/",
	"PATH_TO_GROUP_CREATE" => "/extranet/workgroups/create/",
	"PATH_TO_SEARCH_EXTERNAL" => "/extranet/contacts/index.php",
	"PATH_TO_MESSAGES_CHAT" => "/extranet/contacts/personal/messages/chat/#user_id#/",
	"PATH_TO_USER_CALENDAR" => "/extranet/contacts/personal/user/#user_id#/calendar/",
	"PATH_TO_MESSAGE_FORM_MESS" => "/extranet/contacts/personal/messages/form/#user_id#/#message_id#/",
	"PATH_TO_CONPANY_DEPARTMENT" => "/company/structure.php?set_filter_structure=Y&structure_UF_DEPARTMENT=#ID#",
	"PATH_TO_VIDEO_CALL" => "/extranet/contacts/personal/video/#USER_ID#/",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/extranet/workgroups/",
	"AJAX_MODE" => "N",
	"AJAX_OPTION_SHADOW" => "Y",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_STYLE" => "Y",
	"AJAX_OPTION_HISTORY" => "Y",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"CACHE_TIME_LONG" => "604800",
	"GROUP_THUMBNAIL_SIZE" => 100,
	"PATH_TO_SMILE" => "/bitrix/images/socialnetwork/smile/",
	"PATH_TO_BLOG_SMILE" => "/bitrix/images/blog/smile/",
	"PATH_TO_FORUM_SMILE" => "/bitrix/images/forum/smile/",
	"SONET_PATH_TO_FORUM_ICON" => "/bitrix/images/forum/icon/",
	"SET_TITLE" => "Y",
	"SET_NAV_CHAIN" => "Y",
	"HIDE_OWNER_IN_TITLE" => "Y",
	"USER_PROPERTY_MAIN" => array(
		0 => "UF_1C",
	),
	"USER_PROPERTY_CONTACT" => array(
	),
	"USER_PROPERTY_PERSONAL" => array(
	),
	"AJAX_LONG_TIMEOUT" => "60",
	"BLOG_GROUP_ID" => $GLOBAL_BLOG_GROUP[SITE_ID],
	"FORUM_ID" => $GLOBAL_FORUM_ID["USERS_AND_GROUPS"],//"#FORUM_ID#",
	"CALENDAR_ALLOW_SUPERPOSE" => "Y",
	"CALENDAR_ALLOW_RES_MEETING" => "Y",
	// "CALENDAR_IBLOCK_TYPE" => "events",
	// "CALENDAR_GROUP_IBLOCK_ID" => $GLOBAL_IBLOCK_ID["calendar_groups_extranet"],//"#CALENDAR_IBLOCK_ID#",
	// "CALENDAR_WEEK_HOLIDAYS" => array(
		// 0 => "5",
		// 1 => "6",
	// ),
	// "CALENDAR_YEAR_HOLIDAYS" => "1.01, 2.01, 7.01, 23.02, 8.03, 1.05, 9.05, 12.06, 4.11, 12.12",
	// "CALENDAR_WORK_TIME_START" => "9",
	// "CALENDAR_WORK_TIME_END" => "19",
	// "CALENDAR_ALLOW_SUPERPOSE" => "Y",
	// "CALENDAR_SUPERPOSE_CAL_IDS" => array(),
	// "CALENDAR_SUPERPOSE_CUR_USER_CALS" => "Y",
	// "CALENDAR_SUPERPOSE_USERS_CALS" => "Y",
	// "CALENDAR_SUPERPOSE_GROUPS_CALS" => "Y",
	// "CALENDAR_ALLOW_RES_MEETING" => "N",
	// "CALENDAR_ALLOW_VIDEO_MEETING" => "N",
	"TASK_FORUM_ID" => $GLOBAL_FORUM_ID["GROUPS_AND_USERS_TASKS_COMMENTS_EXTRANET"],// "#TASKS_FORUM_ID#",
	"FILES_GROUP_IBLOCK_TYPE" => "library",
	"FILES_GROUP_IBLOCK_ID" => $GLOBAL_IBLOCK_ID["group_files"],//"#FILES_GROUP_IBLOCK_ID#",
	"FILES_USE_AUTH" => "Y",
	"NAME_FILE_PROPERTY" => "FILE",
	"FILES_UPLOAD_MAX_FILESIZE" => "1024",
	"FILES_UPLOAD_MAX_FILE" => "5",
	"FILES_USE_COMMENTS" => "Y",
	"FILES_FORUM_ID" => $GLOBAL_FORUM_ID["GROUPS_AND_USERS_FILES_COMMENTS"],//"#FILES_FORUM_ID#",
	"FILES_USE_CAPTCHA" => "Y",
	"PHOTO_GROUP_IBLOCK_TYPE" => "photos",
	"PHOTO_GROUP_IBLOCK_ID" => $GLOBAL_IBLOCK_ID["group_photogallery"],//"#PHOTO_GROUP_IBLOCK_ID#",
	"PHOTO_UPLOAD_MAX_FILESIZE" => "64",
	"PHOTO_UPLOAD_MAX_FILE" => "4",
	"PHOTO_ALBUM_PHOTO_THUMBS_SIZE" => "100",
	"PHOTO_ALBUM_PHOTO_SIZE" => "100",
	"PHOTO_THUMBS_SIZE" => "120",
	"PHOTO_PREVIEW_SIZE" => "300",
	"PHOTO_WATERMARK_MIN_PICTURE_SIZE" => "200",
	"PHOTO_PATH_TO_FONT" => "",
	"PHOTO_USE_RATING" => "N",
	"PHOTO_USE_COMMENTS" => "Y",
	"PHOTO_ORIGINAL_SIZE" => "1024",
	"PHOTO_UPLOADER_TYPE" => "form",
	"PHOTO_FORUM_ID" => $GLOBAL_FORUM_ID["PHOTOGALLERY_COMMENTS"],//"#PHOTOGALLERY_FORUM_ID#",
	"PHOTO_USE_CAPTCHA" => "Y",
	"AJAX_OPTION_ADDITIONAL" => "",
	"SEF_URL_TEMPLATES" => array(
		"index" => "index.php",
		"search" => "search.php",
		"group_subscribe" => "group/#group_id#/subscribe/",
		"group" => "group/#group_id#/",
		"group_search" => "group/search/",
		"group_search_subject" => "group/search/#subject_id#/",
		"group_edit" => "group/#group_id#/edit/",
		"group_delete" => "group/#group_id#/delete/",
		"group_request_search" => "group/#group_id#/user_search/",
		"group_request_user" => "group/#group_id#/user/#user_id#/request/",
		"user_request_group" => "group/#group_id#/user_request/",
		"group_requests" => "group/#group_id#/requests/",
		"group_requests_out" => "group/#group_id#/requests_out/",
		"group_mods" => "group/#group_id#/moderators/",
		"group_users" => "group/#group_id#/users/",
		"group_ban" => "group/#group_id#/ban/",
		"user_leave_group" => "group/#group_id#/user_leave/",
		"group_features" => "group/#group_id#/features/",
		"group_photo" => "group/#group_id#/photo/",
		"group_calendar" => "group/#group_id#/calendar/",
		"group_files" => "group/#group_id#/files/#path#",
		"group_blog" => "group/#group_id#/blog/",
		"group_blog_post_edit" => "group/#group_id#/blog/edit/#post_id#/",
		"group_blog_rss" => "group/#group_id#/blog/rss/#type#/",
		"group_blog_draft" => "group/#group_id#/blog/draft/",
		"group_blog_post" => "group/#group_id#/blog/#post_id#/",
		"group_tasks" => "group/#group_id#/tasks/",
		"group_tasks_task" => "group/#group_id#/tasks/task/#action#/#task_id#/",
		"group_tasks_view" => "group/#group_id#/tasks/view/#action#/#view_id#/",
	),
	"LOG_THUMBNAIL_SIZE" => 100,
	"LOG_COMMENT_THUMBNAIL_SIZE" => 100,
	"LOG_NEW_TEMPLATE" => "Y"
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
