CREATE TABLE IF NOT EXISTS b_booking_client_type(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`MODULE_ID` VARCHAR(255) NOT NULL,
	`CODE` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BCT_MODULE_ID_CODE(`MODULE_ID`, `CODE`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_type(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`MODULE_ID` VARCHAR(255) NOT NULL,
	`CODE` VARCHAR(255) DEFAULT NULL,
	`NAME` VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BRT_MODULE_ID_CODE(`MODULE_ID`, `CODE`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_type_notification_settings(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`TYPE_ID` INT UNSIGNED NOT NULL,
	`IS_INFO_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_INFO` VARCHAR(255) NOT NULL,
	`IS_CONFIRMATION_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_CONFIRMATION` VARCHAR(255) NOT NULL,
	`IS_REMINDER_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_REMINDER` VARCHAR(255) NOT NULL,
	`IS_FEEDBACK_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_FEEDBACK` VARCHAR(255) NOT NULL,
	`IS_DELAYED_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_DELAYED` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`TYPE_ID` INT UNSIGNED NOT NULL,
	`EXTERNAL_ID` INT UNSIGNED DEFAULT NULL,
	`IS_MAIN` CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY (`ID`),
	INDEX IX_BR_TYPE_ID(`TYPE_ID`),
	INDEX IX_BR_EXTERNAL_ID(`EXTERNAL_ID`),
	INDEX IX_BR_IS_MAIN(`IS_MAIN`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_data(
	`ID`          INT UNSIGNED    NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`NAME`        VARCHAR(255)    NOT NULL,
	`DESCRIPTION` TEXT,
	`CREATED_AT`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY`  BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BRD_RESOURCE_ID(`RESOURCE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_settings(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`WEEKDAYS` VARCHAR(50) NOT NULL,
	`SLOT_SIZE` INT UNSIGNED DEFAULT NULL,
	`TIME_FROM` INT UNSIGNED NOT NULL,
	`TIME_TO` INT UNSIGNED NOT NULL,
	`TIMEZONE` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_resource_notification_settings(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	`IS_INFO_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_INFO` VARCHAR(255) NOT NULL,
	`IS_CONFIRMATION_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_CONFIRMATION` VARCHAR(255) NOT NULL,
	`IS_REMINDER_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_REMINDER` VARCHAR(255) NOT NULL,
	`IS_FEEDBACK_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_FEEDBACK` VARCHAR(255) NOT NULL,
	`IS_DELAYED_ON` CHAR(1) NOT NULL DEFAULT 'Y',
	`TEMPLATE_TYPE_DELAYED` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) DEFAULT NULL,
	`DATE_FROM` BIGINT UNSIGNED NOT NULL,
	`DATE_TO` BIGINT UNSIGNED NOT NULL,
	`TIMEZONE_FROM` VARCHAR(50) NOT NULL,
	`TIMEZONE_FROM_OFFSET` INT NOT NULL,
	`TIMEZONE_TO` VARCHAR(50) NOT NULL,
	`TIMEZONE_TO_OFFSET` INT NOT NULL,
	`DATE_MAX` BIGINT UNSIGNED NOT NULL,
	`IS_RECURRING` CHAR(1) NOT NULL DEFAULT 'N',
	`RRULE` TEXT,
	`PARENT_ID` INT UNSIGNED DEFAULT NULL,
	`IS_DELETED` CHAR(1) NOT NULL DEFAULT 'N',
	`IS_CONFIRMED` CHAR(1) NOT NULL DEFAULT 'N',
	`DESCRIPTION` TEXT,
	`VISIT_STATUS` VARCHAR(20) NOT NULL DEFAULT 'unknown',
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`CREATED_BY` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX IX_BB_DATE_FROM_DATE_MAX(`DATE_FROM`, `DATE_MAX`),
	INDEX IX_BB_DATE_FROM_DATE_TO(`DATE_FROM`, `DATE_TO`),
	INDEX IX_BB_DATE_FROM(`DATE_FROM`),
	INDEX IX_BB_DATE_MAX(`DATE_MAX`),
	INDEX IX_BB_IS_DELETED(`IS_DELETED`),
	INDEX IX_BB_PARENT_ID (`PARENT_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_resource(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`RESOURCE_ID` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BBR_BOOKING_ID_RESOURCE(`BOOKING_ID`, `RESOURCE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_client(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`CLIENT_TYPE_ID` INT UNSIGNED NOT NULL,
	`CLIENT_ID` INT UNSIGNED NOT NULL,
	`IS_PRIMARY` CHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BBC_BOOKING_ID_CLIENT(`BOOKING_ID`, `CLIENT_TYPE_ID`, `CLIENT_ID`),
	INDEX IX_BBC_CLIENT(`CLIENT_TYPE_ID`, `CLIENT_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_external_data(
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`MODULE_ID` VARCHAR(255) NOT NULL,
	`ENTITY_TYPE_ID` VARCHAR(255) NOT NULL,
	`VALUE`	VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX IX_BBED_BOOKING_ID(`BOOKING_ID`),
	INDEX IX_BBED_VALUE(`MODULE_ID`, `ENTITY_TYPE_ID`, `VALUE`)
);

CREATE TABLE IF NOT EXISTS b_booking_journal(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`ENTITY_ID` BIGINT UNSIGNED NOT NULL,
	`TYPE` VARCHAR(64) NOT NULL,
	`DATA` MEDIUMTEXT NOT NULL,
	`STATUS` VARCHAR(10) NOT NULL,
	`INFO` VARCHAR(512) NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX IX_BJ_ENTITY (`ENTITY_ID`),
	INDEX IX_BJ_TYPE (`TYPE`),
	INDEX IX_BJ_STATUS (`STATUS`),
	INDEX IX_BJ_CREATED_AT (`CREATED_AT`)
);

CREATE TABLE IF NOT EXISTS b_booking_favorites(
	 `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	 `MANAGER_ID` BIGINT UNSIGNED NOT NULL,
	 `RESOURCE_ID` INT UNSIGNED NOT NULL,
	 `TYPE` VARCHAR(10) NOT NULL DEFAULT 'ADDED',
	 PRIMARY KEY (`ID`),
	 INDEX `IX_BF_RESOURCE` (`RESOURCE_ID`),
	 UNIQUE INDEX IX_BF_MANAGER_ID_RESOURCE(`MANAGER_ID`, `RESOURCE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_scorer (
	`ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`USER_ID` INT(11) NOT NULL DEFAULT 0,
	`ENTITY_ID` INT(11) NOT NULL DEFAULT 0,
	`TYPE` VARCHAR(64) NOT NULL DEFAULT '',
	`VALUE` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BS_USER_ID_ENTITY_ID_TYPE(`USER_ID`, `ENTITY_ID`, `TYPE`),
	INDEX `IX_BS_USER` (`USER_ID`),
	INDEX `IX_BS_TYPE` (`TYPE`),
	INDEX `IX_BS_ENTITY` (`ENTITY_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_note(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`DESCRIPTION` TEXT NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX IX_BBN_BOOKING_ID (`BOOKING_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_option (
	ID int auto_increment not null,
	USER_ID int not null,
	NAME varchar(255) not null,
	VALUE varchar(255) not null,
	PRIMARY KEY (ID),
	UNIQUE INDEX ux_bk_option_user_id_name (USER_ID, NAME)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_message(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`NOTIFICATION_TYPE` VARCHAR(255) NOT NULL,
	`SENDER_MODULE_ID` VARCHAR(255) NOT NULL,
	`SENDER_CODE` VARCHAR(255) NOT NULL,
	`EXTERNAL_MESSAGE_ID` BIGINT UNSIGNED NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX IX_BBM_COMPLEX_1 (`BOOKING_ID`, `NOTIFICATION_TYPE`, `SENDER_MODULE_ID`, `SENDER_CODE`, `CREATED_AT`),
	INDEX IX_BBM_MESSAGE(`SENDER_MODULE_ID`, `SENDER_CODE`, `EXTERNAL_MESSAGE_ID`)
);

CREATE TABLE IF NOT EXISTS b_booking_booking_message_failure_log(
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`BOOKING_ID` BIGINT UNSIGNED NOT NULL,
	`NOTIFICATION_TYPE` VARCHAR(255) NOT NULL,
	`SENDER_MODULE_ID` VARCHAR(255) NOT NULL,
	`SENDER_CODE` VARCHAR(255) NOT NULL,
	`REASON_CODE` VARCHAR(255) NOT NULL,
	`REASON_TEXT` TEXT,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX IX_BBMFL_COMPLEX_1 (`BOOKING_ID`, `NOTIFICATION_TYPE`, `SENDER_MODULE_ID`, `SENDER_CODE`, `CREATED_AT`)
);
