<?php
namespace PHPSTORM_META
{
	registerArgumentsSet('bitrix_crm_serviceLocator_codes',
		'crm.service.container',
		'crm.service.localization',
		'crm.service.router',
		'crm.service.context',
		'crm.service.factory.quote',
		'crm.service.factory.deal',
		'crm.service.factory.lead',
		'crm.service.factory.contact',
		'crm.service.factory.company',
		'crm.type.factory',
		'crm.service.converter.ormObject',
		'crm.service.converter.item',
		'crm.service.converter.stage',
		'crm.service.converter.type',
		'crm.service.broker.user',
		'crm.service.broker.company',
		'crm.service.broker.contact',
		'crm.service.director',
		'crm.service.eventhistory',
		'crm.service.typesMap',
		'crm.service.dynamicTypesMap',
		'crm.relation.relationManager',
		'crm.service.broker.typePreset',
		'crm.service.parentFieldManager',
		'crm.service.accounting',
		'crm.service.fileUploader',
		'crm.kanban.entity.lead',
		'crm.kanban.entity.deal',
		'crm.kanban.entity.invoice',
		'crm.kanban.entity.quote',
		'crm.kanban.entity.order',
		'crm.kanban.entity.dynamic',
		'crm.integration.documentgeneratormanager',
		'crm.integration.documentgeneratormanager.productLoader',
		'crm.deal.paymentDocumentsRepository',
		'crm.filter.factory',
		'crm.timeline.timelineEntry.facade',
		'crm.timeline.pusher',
		'crm.timeline.historyDataModel.maker'
	);

	expectedArguments(\Bitrix\Main\DI\ServiceLocator::get(), 0, argumentsSet('bitrix_crm_serviceLocator_codes'));

	override(\Bitrix\Main\DI\ServiceLocator::get(0), map([
		'crm.service.container' => \Bitrix\Crm\Service\Container::class,
		'crm.service.localization' => \Bitrix\Crm\Service\Localization::class,
		'crm.service.router' => \Bitrix\Crm\Service\Router::class,
		'crm.service.context' => \Bitrix\Crm\Service\Context::class,
		'crm.service.factory.quote' => \Bitrix\Crm\Service\Factory\Quote::class,
		'crm.service.factory.deal' => \Bitrix\Crm\Service\Factory\Deal::class,
		'crm.service.factory.lead' => \Bitrix\Crm\Service\Factory\Lead::class,
		'crm.service.factory.contact' => \Bitrix\Crm\Service\Factory\Contact::class,
		'crm.service.factory.company' => \Bitrix\Crm\Service\Factory\Company::class,
		'crm.type.factory' => \Bitrix\Crm\Model\Dynamic\Factory::class,
		'crm.service.converter.ormObject' => \Bitrix\Crm\Service\Converter\OrmObject::class,
		'crm.service.converter.item' => \Bitrix\Crm\Service\Converter\Item::class,
		'crm.service.converter.stage' => \Bitrix\Crm\Service\Converter\Stage::class,
		'crm.service.converter.type' => \Bitrix\Crm\Service\Converter\Type::class,
		'crm.service.broker.user' => \Bitrix\Crm\Service\Broker\User::class,
		'crm.service.broker.company' => \Bitrix\Crm\Service\Broker\Company::class,
		'crm.service.broker.contact' => \Bitrix\Crm\Service\Broker\Contact::class,
		'crm.service.director' => \Bitrix\Crm\Service\Director::class,
		'crm.service.eventhistory' => \Bitrix\Crm\Service\EventHistory::class,
		'crm.service.typesMap' => \Bitrix\Crm\Service\TypesMap::class,
		'crm.service.dynamicTypesMap' => \Bitrix\Crm\Service\DynamicTypesMap::class,
		'crm.relation.relationManager' => \Bitrix\Crm\Relation\RelationManager::class,
		'crm.service.broker.typePreset' => \Bitrix\Crm\Service\Broker\TypePreset::class,
		'crm.service.parentFieldManager' => \Bitrix\Crm\Service\ParentFieldManager::class,
		'crm.service.accounting' => \Bitrix\Crm\Service\Accounting::class,
		'crm.service.fileUploader' => \Bitrix\Crm\Service\FileUploader::class,
		'crm.kanban.entity.lead' => \Bitrix\Crm\Kanban\Entity\Lead::class,
		'crm.kanban.entity.deal' => \Bitrix\Crm\Kanban\Entity\Deal::class,
		'crm.kanban.entity.invoice' => \Bitrix\Crm\Kanban\Entity\Invoice::class,
		'crm.kanban.entity.quote' => \Bitrix\Crm\Kanban\Entity\Quote::class,
		'crm.kanban.entity.order' => \Bitrix\Crm\Kanban\Entity\Order::class,
		'crm.kanban.entity.dynamic' => \Bitrix\Crm\Kanban\Entity\Dynamic::class,
		'crm.integration.documentgeneratormanager' => \Bitrix\Crm\Integration\DocumentGeneratorManager::class,
		'crm.integration.documentgeneratormanager.productLoader' => \Bitrix\Crm\Integration\DocumentGenerator\ProductLoader::class,
		'crm.deal.paymentDocumentsRepository' => \Bitrix\Crm\Deal\PaymentDocumentsRepository::class,
		'crm.filter.factory' => \Bitrix\Crm\Filter\Factory::class,
		'crm.timeline.timelineEntry.facade' => \Bitrix\Crm\Timeline\TimelineEntry\Facade::class,
		'crm.timeline.pusher' => \Bitrix\Crm\Timeline\Pusher::class,
		'crm.timeline.historyDataModel.maker' => \Bitrix\Crm\Timeline\HistoryDataModel\Maker::class,
	]));
}
