<?php
namespace PHPSTORM_META
{
	registerArgumentsSet('bitrix_crm_serviceLocator_codes',
		'crm.service.container',
		'crm.service.localization',
		'crm.service.router',
		'crm.service.context',
		'crm.service.factory.quote',
		'crm.service.factory.deal',
		'crm.service.factory.lead',
		'crm.service.factory.contact',
		'crm.service.factory.company',
		'crm.service.factory.smartInvoice',
		'crm.service.factory.order',
		'crm.type.factory',
		'crm.service.converter.ormObject',
		'crm.service.converter.item',
		'crm.service.converter.stage',
		'crm.service.converter.type',
		'crm.service.converter.productRow',
		'crm.service.converter.category',
		'crm.service.converter.automatedSolution',
		'crm.service.broker.user',
		'crm.service.broker.enumeration',
		'crm.service.broker.file',
		'crm.service.broker.iblockelement',
		'crm.service.broker.iblocksection',
		'crm.service.broker.company',
		'crm.service.broker.contact',
		'crm.service.broker.lead',
		'crm.service.broker.deal',
		'crm.service.broker.order',
		'crm.service.broker.dynamic',
		'crm.service.broker.activity',
		'crm.service.broker.quote',
		'crm.service.activity.badge',
		'crm.service.director',
		'crm.service.eventhistory',
		'crm.service.relation.registrar',
		'crm.service.typesMap',
		'crm.service.dynamicTypesMap',
		'crm.relation.relationManager',
		'crm.service.broker.typePreset',
		'crm.service.parentFieldManager',
		'crm.service.accounting',
		'crm.service.fileUploader',
		'crm.service.multifieldStorage',
		'crm.kanban.entity.lead',
		'crm.kanban.entity.lead.activities',
		'crm.kanban.entity.deal',
		'crm.kanban.entity.deal.activities',
		'crm.kanban.entity.contact',
		'crm.kanban.entity.company',
		'crm.kanban.entity.invoice',
		'crm.kanban.entity.quote',
		'crm.kanban.entity.order',
		'crm.kanban.entity.activity',
		'crm.kanban.entity.dynamic',
		'crm.kanban.entity.smartInvoice',
		'crm.kanban.entity.smartDocument',
		'crm.kanban.entity.smartB2eDocument',
		'crm.listEntity.entity.lead',
		'crm.listEntity.entity.deal',
		'crm.listEntity.entity.invoice',
		'crm.listEntity.entity.quote',
		'crm.listEntity.entity.order',
		'crm.listEntity.entity.activity',
		'crm.listEntity.entity.contact',
		'crm.listEntity.entity.company',
		'crm.listEntity.entity.dynamic',
		'crm.listEntity.entity.smartInvoice',
		'crm.integration.documentgeneratormanager',
		'crm.integration.documentgeneratormanager.productLoader',
		'crm.integration.intranet.toolsManager',
		'crm.integration.rest.eventManager',
		'crm.entity.paymentDocumentsRepository',
		'crm.fieldContext.contextManager',
		'crm.filter.factory',
		'crm.timeline.timelineEntry.facade',
		'crm.timeline.pusher',
		'crm.timeline.historyDataModel.maker',
		'crm.timeline.factory.scheduledItem',
		'crm.timeline.factory.historyItem',
		'crm.timeline.factory.activityItem',
		'crm.conversion.mapper',
		'crm.service.webform.scenario',
		'crm.model.fieldRepository',
		'crm.integration.sign',
		'crm.summary.summaryFactory',
	);

	expectedArguments(\Bitrix\Main\DI\ServiceLocator::get(), 0, argumentsSet('bitrix_crm_serviceLocator_codes'));

	override(\Bitrix\Main\DI\ServiceLocator::get(0), map([
		'crm.service.container' => \Bitrix\Crm\Service\Container::class,
		'crm.service.localization' => \Bitrix\Crm\Service\Localization::class,
		'crm.service.router' => \Bitrix\Crm\Service\Router::class,
		'crm.service.context' => \Bitrix\Crm\Service\Context::class,
		'crm.service.factory.quote' => \Bitrix\Crm\Service\Factory\Quote::class,
		'crm.service.factory.deal' => \Bitrix\Crm\Service\Factory\Deal::class,
		'crm.service.factory.lead' => \Bitrix\Crm\Service\Factory\Lead::class,
		'crm.service.factory.contact' => \Bitrix\Crm\Service\Factory\Contact::class,
		'crm.service.factory.company' => \Bitrix\Crm\Service\Factory\Company::class,
		'crm.service.factory.smartInvoice' => \Bitrix\Crm\Service\Factory\SmartInvoice::class,
		'crm.service.factory.order' => \Bitrix\Crm\Service\Factory\Order::class,
		'crm.type.factory' => \Bitrix\Crm\Model\Dynamic\Factory::class,
		'crm.service.converter.ormObject' => \Bitrix\Crm\Service\Converter\OrmObject::class,
		'crm.service.converter.item' => \Bitrix\Crm\Service\Converter\Item::class,
		'crm.service.converter.stage' => \Bitrix\Crm\Service\Converter\Stage::class,
		'crm.service.converter.type' => \Bitrix\Crm\Service\Converter\Type::class,
		'crm.service.converter.productRow' => \Bitrix\Crm\Service\Converter\ProductRow::class,
		'crm.service.converter.category' => \Bitrix\Crm\Service\Converter\Category::class,
		'crm.service.converter.automatedSolution' => \Bitrix\Crm\Service\Converter\AutomatedSolution::class,
		'crm.service.broker.user' => \Bitrix\Crm\Service\Broker\User::class,
		'crm.service.broker.enumeration' => \Bitrix\Crm\Service\Broker\Enumeration::class,
		'crm.service.broker.file' => \Bitrix\Crm\Service\Broker\File::class,
		'crm.service.broker.iblockelement' => \Bitrix\Crm\Service\Broker\IBlockElement::class,
		'crm.service.broker.iblocksection' => \Bitrix\Crm\Service\Broker\IBLockSection::class,
		'crm.service.broker.company' => \Bitrix\Crm\Service\Broker\Company::class,
		'crm.service.broker.contact' => \Bitrix\Crm\Service\Broker\Contact::class,
		'crm.service.broker.lead' => \Bitrix\Crm\Service\Broker\Lead::class,
		'crm.service.broker.deal' => \Bitrix\Crm\Service\Broker\Deal::class,
		'crm.service.broker.order' => \Bitrix\Crm\Service\Broker\Order::class,
		'crm.service.broker.dynamic' => \Bitrix\Crm\Service\Broker\Dynamic::class,
		'crm.service.broker.activity' => \Bitrix\Crm\Service\Broker\Activity::class,
		'crm.service.broker.quote' => \Bitrix\Crm\Service\Broker\Quote::class,
		'crm.service.director' => \Bitrix\Crm\Service\Director::class,
		'crm.service.eventhistory' => \Bitrix\Crm\Service\EventHistory::class,
		'crm.service.relation.registrar' => \Bitrix\Crm\Relation\Registrar::class,
		'crm.service.typesMap' => \Bitrix\Crm\Service\TypesMap::class,
		'crm.service.dynamicTypesMap' => \Bitrix\Crm\Service\DynamicTypesMap::class,
		'crm.relation.relationManager' => \Bitrix\Crm\Relation\RelationManager::class,
		'crm.service.broker.typePreset' => \Bitrix\Crm\Service\Broker\TypePreset::class,
		'crm.service.parentFieldManager' => \Bitrix\Crm\Service\ParentFieldManager::class,
		'crm.service.accounting' => \Bitrix\Crm\Service\Accounting::class,
		'crm.service.fileUploader' => \Bitrix\Crm\Service\FileUploader::class,
		'crm.service.multifieldStorage' => \Bitrix\Crm\Service\MultifieldStorage::class,
		'crm.kanban.entity.lead' => \Bitrix\Crm\Kanban\Entity\Lead::class,
		'crm.kanban.entity.lead.activities' => \Bitrix\Crm\Kanban\Entity\LeadActivities::class,
		'crm.kanban.entity.deal' => \Bitrix\Crm\Kanban\Entity\Deal::class,
		'crm.kanban.entity.deal.activities' => \Bitrix\Crm\Kanban\Entity\DealActivities::class,
		'crm.kanban.entity.contact' => \Bitrix\Crm\Kanban\Entity\Contact::class,
		'crm.kanban.entity.invoice' => \Bitrix\Crm\Kanban\Entity\Invoice::class,
		'crm.kanban.entity.quote' => \Bitrix\Crm\Kanban\Entity\Quote::class,
		'crm.kanban.entity.order' => \Bitrix\Crm\Kanban\Entity\Order::class,
		'crm.kanban.entity.activity' => \Bitrix\Crm\Kanban\Entity\Activity::class,
		'crm.kanban.entity.dynamic' => \Bitrix\Crm\Kanban\Entity\Dynamic::class,
		'crm.kanban.entity.smartInvoice' => \Bitrix\Crm\Kanban\Entity\SmartInvoice::class,
		'crm.kanban.entity.smartDocument' => \Bitrix\Crm\Kanban\Entity\SmartDocument::class,
		'crm.kanban.entity.smartB2eDocument' => \Bitrix\Crm\Kanban\Entity\SmartB2eDocument::class,
		'crm.listEntity.entity.lead' => \Bitrix\Crm\listEntity\Entity\Lead::class,
		'crm.listEntity.entity.deal' => \Bitrix\Crm\listEntity\Entity\Deal::class,
		'crm.listEntity.entity.invoice' => \Bitrix\Crm\listEntity\Entity\Invoice::class,
		'crm.listEntity.entity.quote' => \Bitrix\Crm\listEntity\Entity\Quote::class,
		'crm.listEntity.entity.order' => \Bitrix\Crm\listEntity\Entity\Order::class,
		'crm.listEntity.entity.activity' => \Bitrix\Crm\listEntity\Entity\Activity::class,
		'crm.listEntity.entity.contact' => \Bitrix\Crm\listEntity\Entity\Contact::class,
		'crm.listEntity.entity.company' => \Bitrix\Crm\listEntity\Entity\Company::class,
		'crm.listEntity.entity.dynamic' => \Bitrix\Crm\listEntity\Entity\Dynamic::class,
		'crm.listEntity.entity.smartInvoice' => \Bitrix\Crm\listEntity\Entity\SmartInvoice::class,
		'crm.integration.documentgeneratormanager' => \Bitrix\Crm\Integration\DocumentGeneratorManager::class,
		'crm.integration.documentgeneratormanager.productLoader' => \Bitrix\Crm\Integration\DocumentGenerator\ProductLoader::class,
		'crm.integration.intranet.toolsManager' => \Bitrix\Crm\Integration\Intranet\ToolsManager::class,
		'crm.integration.rest.eventManager' => \Bitrix\Crm\Integration\Rest\EventManager::class,
		'crm.fieldContext.contextManager' => \Bitrix\Crm\FieldContext\ContextManager::class,
		'crm.entity.paymentDocumentsRepository' => \Bitrix\Crm\Entity\PaymentDocumentsRepository::class,
		'crm.filter.factory' => \Bitrix\Crm\Filter\Factory::class,
		'crm.timeline.timelineEntry.facade' => \Bitrix\Crm\Timeline\TimelineEntry\Facade::class,
		'crm.timeline.pusher' => \Bitrix\Crm\Timeline\Pusher::class,
		'crm.timeline.historyDataModel.maker' => \Bitrix\Crm\Timeline\HistoryDataModel\Maker::class,
		'crm.timeline.factory.scheduledItem' => \Bitrix\Crm\Service\Timeline\Item\Factory\ScheduledItem::class,
		'crm.timeline.factory.historyItem' => \Bitrix\Crm\Service\Timeline\Item\Factory\HistoryItem::class,
		'crm.timeline.factory.activityItem' => \Bitrix\Crm\Service\Timeline\Item\Factory\ConfigurableActivity::class,
		'crm.conversion.mapper' => \Bitrix\Crm\Conversion\Mapper::class,
		'crm.service.webform.scenario' => \Bitrix\Crm\Service\WebForm\WebFormScenarioService::class,
		'crm.model.fieldRepository' => \Bitrix\Crm\Model\FieldRepository::class,
		'crm.integration.sign' => \Bitrix\Crm\Service\Integration\Sign::class,
		'crm.activity.actcounterlighttimerepo' => \Bitrix\Crm\Activity\LightCounter\ActCounterLightTimeRepo::class,
		'crm.summary.summaryFactory' => \Bitrix\Crm\Summary\SummaryFactory::class,
		'crm.binding.clientBinder' => \Bitrix\Crm\Binding\ClientBinder::class,
		'crm.service.communication.rankingFactory' => \Bitrix\Crm\Service\Communication\Search\Ranking\RankingFactory::class,
		'crm.service.integration.im' => \Bitrix\Crm\Integration\Im\ImService::class,
	]));
}
