<?php
$crm_default_option = [
	'path_to_lead_edit' => '/crm/lead/edit/#lead_id#/',
	'path_to_lead_show' => '/crm/lead/show/#lead_id#/',
	'path_to_lead_details' => '/crm/lead/details/#lead_id#/',
	'path_to_lead_list' => '/crm/lead/list/',
	'path_to_lead_convert' => '/crm/lead/convert/',
	'path_to_lead_import' => '/crm/lead/import/',
	'path_to_lead_widget' => '/crm/lead/widget/',
	'path_to_lead_kanban' => '/crm/lead/kanban/',
	'path_to_lead_activity' => '/crm/lead/activity/',
	'path_to_lead_calendar' => '/crm/lead/calendar/',

	'path_to_deal_edit' => '/crm/deal/edit/#deal_id#/',
	'path_to_deal_show' => '/crm/deal/show/#deal_id#/',
	'path_to_deal_details' => '/crm/deal/details/#deal_id#/',
	'path_to_deal_list' => '/crm/deal/list/',
	'path_to_deal_import' => '/crm/deal/import/',
	'path_to_deal_widget' => '/crm/deal/widget/',
	'path_to_deal_kanban' => '/crm/deal/kanban/',
	'path_to_deal_activity' => '/crm/deal/activity/',
	'path_to_deal_calendar' => '/crm/deal/calendar/',

	'path_to_quote_edit' => '/crm/quote/edit/#quote_id#/',
	'path_to_quote_show' => '/crm/quote/show/#quote_id#/',
	'path_to_quote_details' => '/crm/type/7/details/#quote_id#/',
	'path_to_quote_list' => '/crm/quote/list/',
	'path_to_quote_import' => '/crm/quote/import/',
	'path_to_quote_kanban' => '/crm/quote/kanban/',
	'path_to_quote_activity' => '/crm/quote/activity/',
	'path_to_quote_deadlines' => '/crm/quote/deadlines/',

	'path_to_order_details' => '/shop/orders/details/#order_id#/',
	'path_to_order_list' => '/shop/orders/list/',
	'path_to_order_check_details' => '/shop/orders/check/details/#check_id#/',
	'path_to_order_payment_details' => '/shop/orders/payment/details/#payment_id#/',
	'path_to_order_form' => '/shop/orderform/',
	'path_to_order_shipment_details' => '/shop/orders/shipment/details/#shipment_id#/',
	'path_to_order_kanban' => '/shop/orders/kanban/',
	'path_to_order_activity' => '/shop/orders/activity/',
	'path_to_order_import_instagram' => '/shop/import/instagram/',

	'path_to_contact_edit' => '/crm/contact/edit/#contact_id#/',
	'path_to_contact_show' => '/crm/contact/show/#contact_id#/',
	'path_to_contact_details' => '/crm/contact/details/#contact_id#/',
	'path_to_contact_list' => '/crm/contact/list/',
	'path_to_contact_category' => '/crm/contact/category/#category_id#/',
	'path_to_contact_import' => '/crm/contact/import/',
	'path_to_contact_requisite_select' => '/crm/contact/requisite/select/#contact_id#/',

	'path_to_company_edit' => '/crm/company/edit/#company_id#/',
	'path_to_company_show' => '/crm/company/show/#company_id#/',
	'path_to_company_details' => '/crm/company/details/#company_id#/',
	'path_to_company_list' => '/crm/company/list/',
	'path_to_company_category' => '/crm/company/category/#category_id#/',
	'path_to_company_import' => '/crm/company/import/',
	'path_to_company_requisite_select' => '/crm/company/requisite/select/#company_id#/',

	'path_to_user_profile' => '/company/personal/user/#user_id#/',
	'path_to_user_bp' => '/company/personal/bizproc/',

	'path_to_product_edit' => '/crm/product/edit/#product_id#/',
	'path_to_product_show' => '/crm/product/show/#product_id#/',
	'path_to_product_list' => '/crm/product/list/',
	'path_to_product_import' => '/crm/product/import/',

	'path_to_invoice_edit' => '/crm/invoice/edit/#invoice_id#/',
	'path_to_invoice_show' => '/crm/invoice/show/#invoice_id#/',
	'path_to_invoice_payment' => '/crm/invoice/payment/#invoice_id#/',
	'path_to_invoice_list' => '/crm/invoice/list/',
	'path_to_invoice_widget' => '/crm/invoice/widget/',
	'path_to_invoice_kanban' => '/crm/invoice/kanban/',
	'path_to_invoice_activity' => '/crm/invoice/activity/',

	'path_to_activity_list' => '/crm/activity/',
	'path_to_activity_show' => '/crm/activity/?ID=#activity_id#&open_view=#activity_id#',
	'path_to_activity_edit' => '/crm/activity/?ID=#activity_id#&open_edit=#activity_id#',
	'path_to_activity_custom_type_list' => '/crm/configs/custom_activity/',

	'path_to_deal_category' => '/crm/deal/category/#category_id#/',
	'path_to_deal_category_kanban' => '/crm/deal/kanban/category/#category_id#/',
	'path_to_deal_category_activity' => '/crm/deal/activity/category/#category_id#/',
	'path_to_deal_category_list' => '/crm/configs/deal_category/',
	'path_to_deal_category_calendar' => '/crm/deal/calendar/category/#category_id#/',
	'path_to_deal_category_edit' => '/crm/configs/deal_category/?open_edit=#category_id#',

	'path_to_webform_list' => '/crm/webform/list/',
	'path_to_webform_edit' => '/crm/webform/edit/#form_id#/',
	'path_to_webform_fill' => '/pub/form/#form_code#/#form_sec#/',

	'path_to_button_list' => '/crm/button/',
	'path_to_button_edit' => '/crm/button/edit/#id#/',

	'path_to_start' => '/crm/start/',
	'path_to_recycle_bin' => '/crm/recyclebin/',

	'path_to_perm_list' => '/crm/configs/perms/',
	'path_to_config_checker' => '/crm/configs/checker/',
	'path_to_user_field_edit' => '/crm/configs/fields/#entity_id#/edit/#field_id#/',
	'path_to_lead_status_list' => '/crm/type/1/categories/',

	'path_to_store_document_details' => '/shop/documents/details/#store_document_id#/',
	'path_to_shipment_document_details' => '/shop/documents/details/sales_order/#shipment_document_id#/',

	'email_from' => '',
	'email_template' => '',

	'product_catalog_type_id' => '',
	'default_product_catalog_id' => 0,

	'selected_catalog_group_id' => 0,

	'product_row_tax_uniform' => 'Y',

	'enable_slider' => 'Y',
	'enable_simple_time_format' => 'Y',
	'enable_user_name_sorting' => 'N',
	'enable_order_deal_create' => 'N',
	'enable_catalog_price_save' => 'Y',
	'enable_full_catalog' => 'Y',
	'enable_entity_commodity_item_creation' => 'N',
];
