<?php
$phrasesConfig = [
	'encoding' => 'UTF-8',
	'lang' => 'la',
	'phrases' => [
		'CRM_BANK_DETAIL_SECTION_CO_TITLE' => 'Datos bancarios',
		'CRM_BANK_DETAIL_ENTITY_RQ_BANK_NAME_CO_FIELD' => 'Entidad',
		'CRM_BANK_DETAIL_ENTITY_RQ_IIK_CO_FIELD' => 'Código de banco',
		'CRM_BANK_DETAIL_ENTITY_RQ_BANK_ADDR_CO_FIELD' => 'Dirección',
		'CRM_BANK_DETAIL_ENTITY_RQ_BANK_ROUTE_NUM_CO_FIELD' => 'Número de ruta',
		'CRM_BANK_DETAIL_ENTITY_RQ_ACC_NAME_CO_FIELD' => 'Titular de una cuenta',
		//'CRM_BANK_DETAIL_ENTITY_RQ_ACC_TYPE_CO_FIELD' => 'Tipo',
		'CRM_BANK_DETAIL_ENTITY_RQ_ACC_NUM_CO_FIELD' => 'Número de cuenta',
		'CRM_BANK_DETAIL_ENTITY_RQ_SWIFT_CO_FIELD' => 'SWIFT',
		'CRM_BANK_DETAIL_ENTITY_RQ_IBAN_CO_FIELD' => 'IBAN',
		'CRM_BANK_DETAIL_ENTITY_RQ_BIC_CO_FIELD' => 'BIC',
	]
];
