<?php
$phrasesConfig = [
	'encoding' => 'UTF-8',
	'lang' => 'br',
	'phrases' => [
		'CRM_BANK_DETAIL_SECTION_BR_TITLE' => 'Dados bancários',
		'CRM_BANK_DETAIL_ENTITY_RQ_BANK_NAME_BR_FIELD' => 'Banco',
		'CRM_BANK_DETAIL_ENTITY_RQ_BANK_ADDR_BR_FIELD' => 'Endereço do banco',
		'CRM_BANK_DETAIL_ENTITY_RQ_BANK_CODE_BR_FIELD' => 'Código do banco',
		'CRM_BANK_DETAIL_ENTITY_RQ_AGENCY_NAME_BR_FIELD' => 'Agência',
		'CRM_BANK_DETAIL_ENTITY_RQ_BANK_ROUTE_NUM_BR_FIELD' => 'Número de roteamento',
		'CRM_BANK_DETAIL_ENTITY_RQ_ACC_NAME_BR_FIELD' => 'Titular da conta',
		'CRM_BANK_DETAIL_ENTITY_RQ_ACC_NUM_BR_FIELD' => 'Conta',
		'CRM_BANK_DETAIL_ENTITY_RQ_ACC_TYPE_BR_FIELD' => 'Tipo da conta',
		'CRM_BANK_DETAIL_ENTITY_RQ_IBAN_BR_FIELD' => 'IBAN',
		'CRM_BANK_DETAIL_ENTITY_RQ_SWIFT_BR_FIELD' => 'SWIFT',
		'CRM_BANK_DETAIL_ENTITY_RQ_BIC_BR_FIELD' => 'BIC',
	]
];
