<?php
$phrasesConfig = [
	'encoding' => 'UTF-8',
	'lang' => 'pl',
	'phrases' => [
		'CRM_REQUISITE_FIXED_PRESET_COMPANY_PL_TITLE' => 'Organizacja',
		'CRM_REQUISITE_FIXED_PRESET_INDIVIDUAL_PL_TITLE' => 'Jedyny właściciel',
		'CRM_REQUISITE_FIXED_PRESET_LEGALENTITY_PL_TITLE' => 'Firma',
		'CRM_REQUISITE_FIXED_PRESET_PERSON_PL_TITLE' => 'Osoba',
		'CRM_REQUISITE_ENTITY_RQ_COMPANY_NAME_PL_FIELD' => 'Nazwa skrócona',
		'CRM_REQUISITE_ENTITY_RQ_COMPANY_FULL_NAME_PL_FIELD' => 'Nazwa pełna',
		'CRM_REQUISITE_ENTITY_RQ_INN_PL_FIELD' => 'NIP',
		'CRM_REQUISITE_ENTITY_RQ_VAT_ID_PL_FIELD' => 'VAT-EU',
		'CRM_REQUISITE_ENTITY_RQ_REGON_PL_FIELD' => 'REGON',
		'CRM_REQUISITE_ENTITY_RQ_KRS_PL_FIELD' => 'KRS',
		'CRM_REQUISITE_ENTITY_RQ_COMPANY_ID_PL_FIELD' => 'Identyfikator firmy',
		'CRM_REQUISITE_ENTITY_RQ_FIRST_NAME_PL_FIELD' => 'Imię',
		'CRM_REQUISITE_ENTITY_RQ_LAST_NAME_PL_FIELD' => 'Nazwisko',
		'CRM_REQUISITE_ENTITY_RQ_PESEL_PL_FIELD' => 'PESEL',
		'CRM_REQUISITE_ENTITY_RQ_ADDR_PL_FIELD' => 'Adres',
		'CRM_REQUISITE_ENTITY_RQ_SIGNATURE_PL_FIELD' => 'Podpis',
		'CRM_REQUISITE_ENTITY_RQ_STAMP_PL_FIELD' => 'Pieczęć',
	]
];
