<?php
$phrasesConfig = [
	'encoding' => 'UTF-8',
	'lang' => 'fr',
	'phrases' => [
		'CRM_REQUISITE_FIXED_PRESET_COMPANY_FR_TITLE' => 'Organisation',
		'CRM_REQUISITE_FIXED_PRESET_INDIVIDUAL_FR_TITLE' => 'Seul propriétaire',
		'CRM_REQUISITE_FIXED_PRESET_LEGALENTITY_FR_TITLE' => 'Société',
		'CRM_REQUISITE_FIXED_PRESET_PERSON_FR_TITLE' => 'Particulier',
		'CRM_REQUISITE_ENTITY_RQ_COMPANY_NAME_FR_FIELD' => 'Nom',
		'CRM_REQUISITE_ENTITY_RQ_LEGAL_FORM_FR_FIELD' => 'Forme juridique',
		'CRM_REQUISITE_ENTITY_RQ_SIRET_FR_FIELD' => 'Numéro Siret',
		'CRM_REQUISITE_ENTITY_RQ_SIREN_FR_FIELD' => 'Numéro Siren',
		'CRM_REQUISITE_ENTITY_RQ_OKVED_FR_FIELD' => 'Code NAF (APE)',
		'CRM_REQUISITE_ENTITY_RQ_CAPITAL_FR_FIELD' => 'Capital social',
		'CRM_REQUISITE_ENTITY_RQ_RCS_FR_FIELD' => 'RCS',
		'CRM_REQUISITE_ENTITY_RQ_VAT_ID_FR_FIELD' => 'Numéro de TVA intracommunautaire',
		'CRM_REQUISITE_ENTITY_RQ_ADDR_FR_FIELD' => 'Adresse',
		'CRM_REQUISITE_ENTITY_RQ_FIRST_NAME_FR_FIELD' => 'Prénom',
		'CRM_REQUISITE_ENTITY_RQ_LAST_NAME_FR_FIELD' => 'Nom',
		'CRM_REQUISITE_ENTITY_RQ_IDENT_DOC_FR_FIELD' => 'Type de pièce d\'identité',
		'CRM_REQUISITE_ENTITY_RQ_IDENT_DOC_NUM_FR_FIELD' => 'Numéro de pièce d\'identité',
		'CRM_REQUISITE_ENTITY_RQ_SIGNATURE_FR_FIELD' => 'Signature',
		'CRM_REQUISITE_ENTITY_RQ_STAMP_FR_FIELD' => 'Cachet',
	]
];
