<?php
$phrasesConfig = [
	'encoding' => 'utf-8',
	'lang' => 'de',
	'phrases' => [
		'CRM_REQUISITE_FIXED_PRESET_COMPANY_DE_TITLE' => 'Organisation',
		'CRM_REQUISITE_FIXED_PRESET_INDIVIDUAL_DE_TITLE' => 'Selbstständig',
		'CRM_REQUISITE_FIXED_PRESET_LEGALENTITY_DE_TITLE' => 'Unternehmen',
		'CRM_REQUISITE_FIXED_PRESET_PERSON_DE_TITLE' => 'Natürliche Person',
		'CRM_REQUISITE_ENTITY_RQ_NAME_DE_FIELD' => 'Vollständiger Name',
		'CRM_REQUISITE_ENTITY_RQ_FIRST_NAME_DE_FIELD' => 'Vorname',
		'CRM_REQUISITE_ENTITY_RQ_LAST_NAME_DE_FIELD' => 'Name',
		'CRM_REQUISITE_ENTITY_RQ_COMPANY_NAME_DE_FIELD' => 'Name des Unternehmens',
		'CRM_REQUISITE_ENTITY_RQ_ADDR_DE_FIELD' => 'Anschrift',
		'CRM_REQUISITE_ENTITY_RQ_CONTACT_DE_FIELD' => 'Kontaktperson',
		'CRM_REQUISITE_ENTITY_RQ_EMAIL_DE_FIELD' => 'E-Mail ',
		'CRM_REQUISITE_ENTITY_RQ_PHONE_DE_FIELD' => 'Telefonnummer',
		'CRM_REQUISITE_ENTITY_RQ_FAX_DE_FIELD' => 'Fax',
		'CRM_REQUISITE_ENTITY_RQ_INN_DE_FIELD' => 'Steuernummer',
		'CRM_REQUISITE_ENTITY_RQ_USRLE_DE_FIELD' => 'Handelsregisternummer',
		'CRM_REQUISITE_ENTITY_RQ_VAT_ID_DE_FIELD' => 'UmSt.-IdNr.',
		'CRM_REQUISITE_ENTITY_RQ_SIGNATURE_DE_FIELD' => 'Signatur',
		'CRM_REQUISITE_ENTITY_RQ_STAMP_DE_FIELD' => 'Stempel',
	]
];
