<?php
$phrasesConfig = [
	'encoding' => 'UTF-8',
	'lang' => 'br',
	'phrases' => [
		'CRM_REQUISITE_FIXED_PRESET_COMPANY_BR_TITLE' => 'Empresa',
		'CRM_REQUISITE_FIXED_PRESET_INDIVIDUAL_BR_TITLE' => 'Autônomo',
		'CRM_REQUISITE_FIXED_PRESET_LEGALENTITY_BR_TITLE' => 'Pessoa jurídica',
		'CRM_REQUISITE_FIXED_PRESET_PERSON_BR_TITLE' => 'Pessoa física',
		'CRM_REQUISITE_ENTITY_RQ_CNPJ_BR_FIELD' => 'CNPJ',
		'CRM_REQUISITE_ENTITY_RQ_COMPANY_NAME_BR_FIELD' => 'Razão Social',
		'CRM_REQUISITE_ENTITY_RQ_STATE_REG_BR_FIELD' => 'Inscrição Estadual (IE)',
		'CRM_REQUISITE_ENTITY_RQ_MNPL_REG_BR_FIELD' => 'Inscrição Municipal (IM)',
		'CRM_REQUISITE_ENTITY_RQ_ADDR_BR_FIELD' => 'Endereço',
		'CRM_REQUISITE_ENTITY_RQ_CPF_BR_FIELD' => 'CPF',
		'CRM_REQUISITE_ENTITY_RQ_FIRST_NAME_BR_FIELD' => 'Primeiro Nome',
		'CRM_REQUISITE_ENTITY_RQ_LAST_NAME_BR_FIELD' => 'Sobrenome',
		'CRM_REQUISITE_ENTITY_RQ_IDENT_DOC_NUM_BR_FIELD' => 'RG',
		'CRM_REQUISITE_ENTITY_RQ_SIGNATURE_BR_FIELD' => 'Assinatura',
		'CRM_REQUISITE_ENTITY_RQ_STAMP_BR_FIELD' => 'Carimbo',
	]
];
