<?php

return [
	'extensions' => [
		'crm:timeline/item/ui/body/blocks/audio-block',
		'crm:timeline/item/ui/body/blocks/base',
		'crm:timeline/item/ui/body/blocks/base-editable-block',
		'crm:timeline/item/ui/body/blocks/client-mark',
		'crm:timeline/item/ui/body/blocks/comment-content',
		'crm:timeline/item/ui/body/blocks/date-block',
		'crm:timeline/item/ui/body/blocks/date-pill',
		'crm:timeline/item/ui/body/blocks/editable-description',
		'crm:timeline/item/ui/body/blocks/file-list',
		'crm:timeline/item/ui/body/blocks/line-of-text-blocks',
		'crm:timeline/item/ui/body/blocks/link-block',
		'crm:timeline/item/ui/body/blocks/note',
		'crm:timeline/item/ui/body/blocks/player-alert',
		'crm:timeline/item/ui/body/blocks/text-block',
		'crm:timeline/item/ui/body/blocks/value-change',
		'crm:timeline/item/ui/body/blocks/with-title',
		'crm:timeline/item/ui/body/blocks/sharing-slots-list',
		'crm:timeline/item/ui/body/blocks/money-pill',
		'crm:timeline/item/ui/body/blocks/money',
		'crm:timeline/item/ui/body/blocks/ecommerce-documents-list',
		'crm:timeline/item/ui/body/blocks/sms-message',
		'crm:timeline/item/ui/body/blocks/mail-contact-list',
		'crm:timeline/item/ui/body/blocks/item-selector',
		'crm:timeline/item/ui/body/blocks/address-block',
		'money',
	],
];
