<?php

return [
	'extensions' => [
		'apptheme',
		'assets/icons',
		'bbcode/ast-processor',
		'bbcode/parser',
		'bottom-sheet',
		'event-emitter',
		'layout/ui/fields/file/theme/air',
		'loc',
		'recipient',
		'type',
        'tokens',
		'assets/icons',
		'ui-system/form/buttons/button',
        'layout/ui/context-menu',
        'alert',
        'haptics',
        'in-app-url',
        'utils/copy',
        'utils/file',
	],

	'bundle' => [
		'src/components/text-input',
		'src/components/toolbar',
		'src/components/toolbar-button',
		'src/icons',
		'src/entity-selector',
		'src/entities/mention',
		'src/adapters/base-adapter',
		'src/adapters/disk-adapter',
		'src/adapters/code-adapter',
		'src/adapters/quote-adapter',
		'src/adapters/image-adapter',
		'src/adapters/table-adapter',
		'src/adapters/mention-adapter',
        'src/internal/parser',
        'src/internal/scheme',
        'src/svgom/svg-node',
        'src/svgom/svg-root-node',
        'src/svgom/svg-text-node',
        'src/bbcode-view/bbcode-view',
	],
];
