export const ERROR_CODE_FORM_READ_ACCESS_DENIED = 1;
export const ERROR_CODE_FORM_WRITE_ACCESS_DENIED = 2;
export const ERROR_CODE_WIDGET_READ_ACCESS_DENIED = 3;
export const ERROR_CODE_WIDGET_WRITE_ACCESS_DENIED = 4;
export const ERROR_CODE_OPENLINES_READ_ACCESS_DENIED = 5;
export const ERROR_CODE_OPENLINES_WRITE_ACCESS_DENIED = 6;