<?php

namespace Bitrix\Crm\Item;

class SmartB2eDocument extends Dynamic
{
	public const FIELD_NAME_NUMBER = 'NUMBER';
	public const FIELD_NAME_TITLE = 'TITLE';
	public const FIELD_NAME_CREATED_TIME = 'CREATED_TIME';
	public const FIELD_NAME_ASSIGNEE_MEMBER = 'ASSIGNEE_MEMBER';
	public const FIELD_NAME_REVIEWER_MEMBER_LIST = 'REVIEWER_MEMBER_LIST';
	public const FIELD_NAME_EDITOR_MEMBER_LIST = 'EDITOR_MEMBER_LIST';
	public const FIELD_NAME_NOT_SIGNED_EMPLOYER_LIST = 'NOT_SIGNED_EMPLOYER_LIST';
	public const FIELD_NAME_NOT_SIGNED_COMPANY_LIST = 'NOT_SIGNED_COMPANY_LIST';
	public const FIELD_NAME_EMPLOYER_LIST = 'EMPLOYER_LIST';
	public const FIELD_NAME_SIGN_CANCELLED_MEMBER_LIST = 'SIGN_CANCELLED_MEMBER_LIST';
	public const FIELD_NAME_SIGN_CANCELLED_MEMBER = 'SIGN_CANCELLED_MEMBER';
	public const FIELD_NAME_SIGN_RESULT_STATUS = 'SIGN_RESULT_STATUS';
}
