<?php

namespace Bitrix\Crm\Quote;

use Bitrix\Sale;
use Bitrix\Main;

if (!Main\Loader::includeModule('sale'))
{
	return;
}

/**
 * Class Basket
 * @package Bitrix\Crm\Quote
 */
class BasketPropertiesCollection extends Sale\BasketPropertiesCollectionBase
{
	/**
	 * @throws Main\NotImplementedException
	 */
	public static function getRegistryType()
	{
		return REGISTRY_TYPE_CRM_QUOTE;
	}

	/**
	 * Load basket item properties.
	 *
	 * @param array $parameters orm getList parameters.
	 * @return \Bitrix\Main\DB\Result
	 */
	public static function getList(array $parameters = array())
	{
		parent::getList($parameters); // TODO: Change the autogenerated stub
	}

	/**
	 * Delete basket item properties.
	 *
	 * @param $primary
	 * @throws Main\NotImplementedException
	 * @return Main\Entity\DeleteResult
	 */
	protected static function delete($primary)
	{
		parent::delete($primary); // TODO: Change the autogenerated stub
	}

}