
CREATE TABLE b_im_bot_network_session (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	BOT_ID int DEFAULT 0,
	DIALOG_ID varchar(50),
	SESSION_ID int DEFAULT 0,
	GREETING_SHOWN char(1) NOT NULL DEFAULT 'N',
	MENU_STATE text,
	DATE_CREATE timestamp NOT NULL DEFAULT current_timestamp,
	DATE_FINISH timestamp DEFAULT null,
	DATE_LAST_ACTIVITY timestamp DEFAULT current_timestamp,
	CLOSE_TERM int DEFAULT 1440,
	TELEMETRY_SENT char(1) NOT NULL DEFAULT 'N',
	STATUS varchar(50),
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_im_bot_network_session_bot_id_dialog_id ON b_im_bot_network_session (bot_id, dialog_id);
