<?php

return [
	'extensions' => [
		'animation/components/fade-view',
		'assets/icons',
		'alert',
		'analytics',
		'device/connection',
		'asset-manager',
		'feature',
		'toast',
		'haptics',
		'notify',
		'ui-system/form/buttons/button',
		'ui-system/blocks/icon',
		'ui-system/blocks/badges/counter',
		'ui-system/blocks/chips/chip-button',
		'ui-system/blocks/chips/chip-status',
		'ui-system/blocks/status-block',
		'tokens',
		'pull/client/events',
		'utils/object',
		'utils/validation',
		'utils/date',
		'utils/date/formats',
		'utils/guid',
		'utils/function',

		'rest',
		'rest/run-action-executor',

		'layout/pure-component',
		'layout/ui/loading-screen',
		'layout/ui/form',
		'layout/ui/fields/textarea/theme/air-title',
		'layout/ui/fields/textarea/theme/air-description',
		'layout/ui/fields/project/theme/air',
		'layout/ui/fields/project/theme/air-compact',
		'layout/ui/fields/user/theme/air',
		'layout/ui/fields/user/theme/air-compact',
		'layout/ui/fields/tag/theme/air',
		'layout/ui/fields/tag/theme/air-compact',
		'layout/ui/fields/crm-element/theme/air',
		'layout/ui/fields/crm-element/theme/air-compact',
		'layout/ui/fields/file-with-background-attach/theme/air',
		'layout/ui/fields/file-with-background-attach/theme/air-compact',
		'tasks:layout/fields/subtask/theme/air',
		'tasks:layout/fields/subtask/theme/air-compact',
		'tasks:layout/fields/related-task/theme/air',
		'tasks:layout/fields/related-task/theme/air-compact',
		'tasks:layout/fields/time-tracking',
		'tasks:layout/fields/time-tracking/theme/air-compact',
		'tasks:layout/fields/stage-selector',

		'statemanager/redux/store',
		'statemanager/redux/connect',
		'statemanager/redux/batched-actions',
		'statemanager/redux/slices/users',
		'tariff-plan-restriction',

		'tasks:loc',
		'tasks:enum',
		'tasks:disk',
		'tasks:fields/restriction',

		'tasks:layout/checklist/preview',
		'tasks:layout/fields/checklist/theme/air-compact',
		'tasks:checklist/controller',
		'tasks:layout/fields/deadline/theme/air',
		'tasks:layout/fields/result/theme/air',
		'tasks:layout/fields/result/theme/air-compact',
		'tasks:layout/fields/flow/theme/air',
		'tasks:layout/fields/flow/theme/air-compact',
		'tasks:layout/fields/date-plan/theme/air',
		'tasks:layout/fields/date-plan/theme/air-compact',
		'tasks:layout/fields/user-fields/theme/air',
		'tasks:layout/fields/user-fields/theme/air-compact',
		'tasks:layout/action-menu',
		'tasks:layout/action-menu/actions',
		'tasks:layout/online',

		'tasks:statemanager/redux/slices/tasks',
		'tasks:statemanager/redux/slices/tasks/observers/creation-error-observer',
		'tasks:statemanager/redux/slices/tasks-results',
		'tasks:statemanager/redux/slices/groups',
		'tasks:statemanager/redux/slices/flows',
		'tasks:statemanager/redux/slices/tasks-stages',
		'tasks:statemanager/redux/slices/kanban-settings',
		'tasks:statemanager/redux/slices/kanban-settings/action',
		'tasks:statemanager/redux/slices/tasks-stages',

		'tasks:statemanager/redux/slices/tasks-stages/thunk',

		'tasks:layout/task/form-utils',
		'type',
	],
	'bundle' => [
		'./ui/likes-panel',
		'./ui/comments-button',
		'./ui/action-buttons',
		'./ui/status-badge',
		'./ui/task-edit-form',
		'./services/access-toast',
		'./services/layout-buttons',
		'./services/deadline-format',
		'./services/pull-listener',
		'./services/comments-opener',
		'./services/sticky-title',
		'./services/data-provider',
	],
];
