/** @lang MySQL */
CREATE TABLE IF NOT EXISTS `b_hr_structure_node_backward_access_code`
(
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`NODE_ID` bigint NOT NULL,
	`ACCESS_CODE` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX UX_B_HR_STRUCTURE_NODE_BACKWARD_ACCESS_CODE_ACCESS_CODE (`ACCESS_CODE`),
	INDEX IX_B_HR_STRUCTURE_NODE_BACKWARD_ACCESS_CODE_NODE_ID (NODE_ID)
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_member_role`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`MEMBER_ID` bigint NOT NULL,
	`ROLE_ID` bigint NOT NULL,
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX IX_B_HR_STRUCTURE_NODE_MEMBER_ROLE_MEMBER_ID (MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_member`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`ENTITY_TYPE` varchar(50) NOT NULL DEFAULT 'USER',
	`ENTITY_ID` bigint NOT NULL,
	`ACTIVE` varchar(1) default 'Y',
	`NODE_ID` bigint NOT NULL,
	`ADDED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE INDEX UX_B_HR_NODE_MEMBER_NODE_ID_ENTITY_TYPE_ENTITY_ID (`NODE_ID`, `ENTITY_TYPE`, `ENTITY_ID`),
	INDEX IX_B_HR_NODE_MEMBER_ENTITY_TYPE_ENTITY_ID (`ENTITY_TYPE`, `ENTITY_ID`)
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_relation`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NODE_ID` bigint NOT NULL,
	`ENTITY_ID` bigint NOT NULL,
	`ENTITY_TYPE` varchar(50) NOT NULL,
	`WITH_CHILD_NODES` varchar(1) default 'N',
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX B_HR_STRUCTURE_NODE_RELATION_IX (NODE_ID, ENTITY_TYPE, ENTITY_ID, WITH_CHILD_NODES),
	INDEX B_HR_STRUCTURE_NODE_RELATION_ENTITY_TYPE_ENTITY_ID_IX  (ENTITY_TYPE, ENTITY_ID)
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_role`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NODE_ID` bigint NOT NULL,
	`ROLE_ID` bigint NOT NULL,
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `b_hr_structure`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NAME` varchar(255) NOT NULL,
	`TYPE` varchar(50) NOT NULL DEFAULT 'DEFAULT',
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`XML_ID` varchar(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node` (
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NAME` varchar(255) NOT NULL,
	`TYPE` varchar(50) NOT NULL,
	`STRUCTURE_ID` bigint NOT NULL,
	`PARENT_ID` bigint,
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`XML_ID` varchar(255),
	`ACTIVE` varchar(1) NOT NULL DEFAULT 'Y',
	`GLOBAL_ACTIVE`  varchar(1) NOT NULL DEFAULT 'Y',
	`SORT` int NOT NULL DEFAULT 500,
	`DESCRIPTION` varchar(255) NULL DEFAULT NULL,
	INDEX IX_B_HR_STRUCTURE_NODE_SORT (SORT),
	INDEX B_HR_STRUCTURE_NODE_XML_ID_IX (XML_ID),
	INDEX IX_B_HR_STRUCTURE_NODE_STRUCTURE_ID_PARENT_ID (STRUCTURE_ID, PARENT_ID)
);

CREATE TABLE IF NOT EXISTS  `b_hr_structure_node_path` (
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`PARENT_ID` bigint NOT NULL,
	`CHILD_ID` bigint NOT NULL,
	`DEPTH` bigint NOT NULL,
	UNIQUE INDEX UX_B_HR_NODE_PATH_PARENT_ID_CHILD_ID (`PARENT_ID`, `CHILD_ID`)
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_role` (
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`ENTITY_TYPE` varchar(255) NOT NULL,
	`NAME` varchar(255) NOT NULL,
	`PRIORITY` bigint NOT NULL,
	`CHILD_AFFECTION_TYPE` int NOT NULL,
	`XML_ID` varchar(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS b_hr_access_role (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME varchar(250) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_hr_access_role_relation (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID int UNSIGNED NOT NULL,
	RELATION varchar(8) NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_B_HR_ACCESS_ROLE_RELATION_ROLE_ID (ROLE_ID),
	INDEX IX_B_HR_ACCESS_ROLE_RELATION_RELATION (RELATION)
);

CREATE TABLE IF NOT EXISTS b_hr_access_permission (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID int UNSIGNED NOT NULL,
	PERMISSION_ID varchar(32) NOT NULL,
	VALUE tinyint UNSIGNED NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_B_HR_ACCESS_PERMISSION_ROLE_ID (ROLE_ID),
	INDEX IX_B_HR_ACCESS_PERMISSION_PERMISSION_ID (PERMISSION_ID),
	UNIQUE (ROLE_ID, PERMISSION_ID)
);

CREATE TABLE IF NOT EXISTS b_hr_log (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	DATE_CREATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MESSAGE varchar(255) DEFAULT NULL,
	ENTITY_TYPE varchar(50) DEFAULT NULL,
	ENTITY_ID bigint DEFAULT NULL,
	USER_ID int DEFAULT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_HR_LOG_ENTITY_ID(ENTITY_ID),
	INDEX IX_B_HR_LOG_USER_ID(USER_ID)
);

CREATE TABLE IF NOT EXISTS `b_hr_hcmlink_company` (
	`ID` int unsigned NOT NULL AUTO_INCREMENT,
	`MY_COMPANY_ID` int unsigned NOT NULL,
	`CODE` varchar(255) NOT NULL,
	`TITLE` varchar(255) NOT NULL,
	`DATA` text NOT NULL,
	`CREATED_AT` datetime DEFAULT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `IX_B_HR_INTEGRATION_COMPANY` (`CODE`)
);

CREATE TABLE IF NOT EXISTS `b_hr_hcmlink_employee` (
	`ID` int unsigned NOT NULL AUTO_INCREMENT,
	`PERSON_ID` int unsigned NOT NULL,
	`CODE` varchar(255) NOT NULL,
	`DATA` text NOT NULL,
	`CREATED_AT` datetime DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `IX_B_HR_INTEGRATION_PERSON` (`PERSON_ID`),
	UNIQUE KEY `IX_B_HR_INTEGRATION_PERSON_EMPLOYEE` (`PERSON_ID`,`CODE`)
);

CREATE TABLE IF NOT EXISTS `b_hr_hcmlink_field` (
	`ID` int unsigned NOT NULL AUTO_INCREMENT,
	`COMPANY_ID` int unsigned NOT NULL,
	`CODE` varchar(255) NOT NULL,
	`TYPE` smallint NOT NULL DEFAULT '0',
	`ENTITY_TYPE` smallint NOT NULL DEFAULT '0',
	`TTL` int NOT NULL DEFAULT '86400',
	`TITLE` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `IX_B_HR_INTEGRATION_COMPANY_FIELD` (`COMPANY_ID`,`CODE`)
);

CREATE TABLE IF NOT EXISTS `b_hr_hcmlink_field_value` (
	`ID` int unsigned NOT NULL AUTO_INCREMENT,
	`EMPLOYEE_ID` int unsigned NOT NULL,
	`FIELD_ID` int unsigned NOT NULL,
	`VALUE` varchar(255) NOT NULL,
	`EXPIRED_AT` datetime DEFAULT NULL,
	`CREATED_AT` datetime DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `IX_B_HR_HCMLINK_FIELD_VALUE_EXPIRED_AT` (`EXPIRED_AT`),
	UNIQUE INDEX UX_B_HR_INTEGRATION_EMPLOYEE_FIELD (`EMPLOYEE_ID`,`FIELD_ID`)
);

CREATE TABLE IF NOT EXISTS `b_hr_hcmlink_job` (
	`ID` int unsigned NOT NULL AUTO_INCREMENT,
	`COMPANY_ID` int unsigned NOT NULL,
	`TYPE` smallint NOT NULL DEFAULT '0',
	`STATUS` smallint NOT NULL DEFAULT '0',
	`PROGRESS_RECEIVED` int unsigned NOT NULL DEFAULT '0',
	`PROGRESS_TOTAL` int unsigned NOT NULL DEFAULT '0',
	`INPUT_DATA` text NOT NULL,
	`OUTPUT_DATA` text NOT NULL,
	`EVENT_COUNT` int DEFAULT 0 NOT NULL,
	`CREATED_AT` datetime DEFAULT NULL,
	`UPDATED_AT` datetime DEFAULT NULL,
	`FINISHED_AT` datetime DEFAULT NULL,
	PRIMARY KEY (`ID`),
	INDEX `IX_B_HR_HCMLINK_JOB_COMPANY_ID` (`COMPANY_ID`),
	INDEX `IX_B_HR_HCMLINK_JOB_STATUS` (`STATUS`),
	INDEX `IX_B_HR_HCMLINK_JOB_UPDATED_AT` (`UPDATED_AT`),
	INDEX `IX_B_HR_HCMLINK_JOB_CREATED_AT` (`CREATED_AT`)
);

CREATE TABLE IF NOT EXISTS `b_hr_hcmlink_person` (
	`ID` int unsigned NOT NULL AUTO_INCREMENT,
	`COMPANY_ID` int unsigned NOT NULL,
	`USER_ID` int unsigned DEFAULT NULL,
	`CODE` varchar(255) NOT NULL,
	`TITLE` varchar(255) NOT NULL,
	`CREATED_AT` datetime DEFAULT NULL,
	`UPDATED_AT` datetime DEFAULT NULL,
	`MATCH_COUNTER` int DEFAULT 0 NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY `IX_B_HR_INTEGRATION_COMPANY_PERSON` (`COMPANY_ID`,`CODE`),
	INDEX `IX_B_HR_INTEGRATION_COMPANY_USER` (`COMPANY_ID`,`USER_ID`),
	INDEX `IX_B_HR_INTEGRATION_PERSON_USER_COMPANY` (`USER_ID`,`COMPANY_ID`)
);

CREATE TABLE IF NOT EXISTS `b_hr_hcmlink_person_index` (
	`PERSON_ID` int NOT NULL,
	`SEARCH_CONTENT` TEXT NULL,
	PRIMARY KEY (`PERSON_ID`)
);