
CREATE TABLE b_intranet_sharepoint (
  IBLOCK_ID int NOT NULL,
  SP_LIST_ID varchar(32) NOT NULL,
  SP_URL varchar(255) NOT NULL,
  SP_AUTH_USER varchar(50) DEFAULT '',
  SP_AUTH_PASS varchar(50) DEFAULT '',
  SYNC_DATE timestamp,
  SYNC_PERIOD int DEFAULT 86400,
  SYNC_ERRORS int DEFAULT 0,
  SYNC_LAST_TOKEN varchar(100) DEFAULT '',
  SYNC_PAGING varchar(100) DEFAULT '',
  HANDLER_MODULE varchar(50) DEFAULT '',
  HANDLER_CLASS varchar(100) DEFAULT '',
  PRIORITY char(1) DEFAULT 'B',
  PRIMARY KEY (IBLOCK_ID)
);

CREATE TABLE b_intranet_sharepoint_field (
  IBLOCK_ID int NOT NULL,
  FIELD_ID varchar(50) NOT NULL,
  SP_FIELD varchar(50) NOT NULL,
  SP_FIELD_TYPE varchar(50) NOT NULL,
  SETTINGS text,
  PRIMARY KEY (IBLOCK_ID, FIELD_ID)
);

CREATE TABLE b_intranet_sharepoint_queue (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IBLOCK_ID int NOT NULL,
  SP_METHOD varchar(100) NOT NULL,
  SP_METHOD_PARAMS text,
  CALLBACK text,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_intranet_sharepoint_queue_iblock_id ON b_intranet_sharepoint_queue (iblock_id);

CREATE TABLE b_intranet_sharepoint_log (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IBLOCK_ID int NOT NULL,
  ELEMENT_ID int NOT NULL,
  VERSION int DEFAULT 0,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_intranet_sharepoint_log_iblock_id_element_id ON b_intranet_sharepoint_log (iblock_id, element_id);

CREATE TABLE b_rating_subordinate (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  RATING_ID int NOT NULL,
  ENTITY_ID int NOT NULL,
  VOTES decimal DEFAULT '0.0000',
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_rating_subordinate_rating_id_entity_id ON b_rating_subordinate (rating_id, entity_id);

CREATE TABLE b_intranet_ustat_hour (
  USER_ID int NOT NULL,
  HOUR timestamp NOT NULL,
  TOTAL int NOT NULL DEFAULT '0',
  SOCNET int NOT NULL DEFAULT '0',
  LIKES int NOT NULL DEFAULT '0',
  TASKS int NOT NULL DEFAULT '0',
  IM int NOT NULL DEFAULT '0',
  DISK int NOT NULL DEFAULT '0',
  MOBILE int NOT NULL DEFAULT '0',
  CRM int NOT NULL DEFAULT '0',
  PRIMARY KEY (USER_ID, HOUR)
);
CREATE INDEX ix_b_intranet_ustat_hour_hour ON b_intranet_ustat_hour (hour);

CREATE TABLE b_intranet_ustat_day (
  USER_ID int NOT NULL,
  DAY date NOT NULL,
  TOTAL int NOT NULL DEFAULT '0',
  SOCNET int NOT NULL DEFAULT '0',
  LIKES int NOT NULL DEFAULT '0',
  TASKS int NOT NULL DEFAULT '0',
  IM int NOT NULL DEFAULT '0',
  DISK int NOT NULL DEFAULT '0',
  MOBILE int NOT NULL DEFAULT '0',
  CRM int NOT NULL DEFAULT '0',
  PRIMARY KEY (USER_ID, DAY)
);
CREATE INDEX ix_b_intranet_ustat_day_day ON b_intranet_ustat_day (day);

CREATE TABLE b_intranet_dstat_hour (
  DEPT_ID int NOT NULL,
  HOUR timestamp NOT NULL,
  TOTAL int8 NOT NULL DEFAULT '0',
  SOCNET int8 NOT NULL DEFAULT '0',
  LIKES int8 NOT NULL DEFAULT '0',
  TASKS int8 NOT NULL DEFAULT '0',
  IM int8 NOT NULL DEFAULT '0',
  DISK int8 NOT NULL DEFAULT '0',
  MOBILE int8 NOT NULL DEFAULT '0',
  CRM int8 NOT NULL DEFAULT '0',
  PRIMARY KEY (DEPT_ID, HOUR)
);
CREATE INDEX ix_b_intranet_dstat_hour_hour ON b_intranet_dstat_hour (hour);

CREATE TABLE b_intranet_dstat_day (
  DEPT_ID int NOT NULL,
  DAY date NOT NULL,
  ACTIVE_USERS int8 NOT NULL DEFAULT '0',
  INVOLVEMENT int NOT NULL DEFAULT '0',
  TOTAL int8 NOT NULL DEFAULT '0',
  SOCNET int8 NOT NULL DEFAULT '0',
  LIKES int8 NOT NULL DEFAULT '0',
  TASKS int8 NOT NULL DEFAULT '0',
  IM int8 NOT NULL DEFAULT '0',
  DISK int8 NOT NULL DEFAULT '0',
  MOBILE int8 NOT NULL DEFAULT '0',
  CRM int8 NOT NULL DEFAULT '0',
  PRIMARY KEY (DEPT_ID, DAY)
);
CREATE INDEX ix_b_intranet_dstat_day_day ON b_intranet_dstat_day (day);

CREATE TABLE b_intranet_queue (
  ENTITY_TYPE varchar(20) NOT NULL,
  ENTITY_ID varchar(10) NOT NULL,
  LAST_ITEM varchar(255) NOT NULL,
  PRIMARY KEY (ENTITY_TYPE, ENTITY_ID)
);

CREATE TABLE b_intranet_invitation (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  USER_ID int NOT NULL,
  ORIGINATOR_ID int NOT NULL,
  INVITATION_TYPE varchar(50),
  DATE_CREATE timestamp NOT NULL,
  INITIALIZED char(1) NOT NULL DEFAULT 'N',
  IS_MASS char(1) NOT NULL DEFAULT 'N',
  IS_DEPARTMENT char(1) NOT NULL DEFAULT 'N',
  IS_INTEGRATOR char(1) NOT NULL DEFAULT 'N',
  IS_REGISTER char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_intranet_invitation_date_create ON b_intranet_invitation (date_create);
CREATE UNIQUE INDEX ux_b_intranet_invitation_user_id_originator_id ON b_intranet_invitation (user_id, originator_id);

CREATE TABLE b_intranet_theme (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  THEME_ID varchar(100) NOT NULL,
  USER_ID int NOT NULL,
  ENTITY_TYPE varchar(50) NOT NULL,
  ENTITY_ID int NOT NULL,
  CONTEXT varchar(100) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_intranet_theme_entity_type_entity_id_context ON b_intranet_theme (entity_type, entity_id, context);

CREATE TABLE b_intranet_custom_section (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CODE varchar(255) NOT NULL,
  TITLE varchar(255) NOT NULL,
  MODULE_ID varchar(50) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_intranet_custom_section_code ON b_intranet_custom_section (code);
CREATE INDEX ix_b_intranet_custom_section_module_id ON b_intranet_custom_section (module_id);

CREATE TABLE b_intranet_custom_section_page (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CUSTOM_SECTION_ID int8 NOT NULL,
  CODE varchar(255) NOT NULL,
  TITLE varchar(255) NOT NULL,
  SORT int NOT NULL,
  MODULE_ID varchar(50) NOT NULL,
  SETTINGS varchar(255) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX ix_b_intranet_custom_section_page_module_id_settings ON b_intranet_custom_section_page (module_id, settings);

CREATE TABLE b_intranet_invitation_link
(
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ENTITY_TYPE varchar(15) NOT NULL,
	ENTITY_ID int NOT NULL,
	CODE varchar(64) NOT NULL,
	CREATED_BY int,
	CREATED_AT timestamp NOT NULL,
	EXPIRED_AT timestamp,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_intranet_invitation_link_entity_type_entity_id ON b_intranet_invitation_link (entity_type, entity_id);