<?php

return [
	'extensions' => [
		'tokens',
		'loc',
		'type',
		'haptics',
		'utils/date/formats',
		'utils/date',
		'utils/url',
		'utils/skeleton',
		'utils/function',
		'helpers/component',
		'pull/client/events',
		'bottom-sheet',
		'tariff-plan-restriction',
		'layout/pure-component',
		'assets/icons',
		'layout/ui/scroll-view',
		'haptics',

		'ui-system/blocks/icon',
		'ui-system/blocks/badges/counter',
		'ui-system/blocks/badges/status',
		'ui-system/blocks/switcher',
		'ui-system/blocks/icon',
		'ui-system/layout/box',
		'ui-system/layout/area',
		'ui-system/layout/card',
		'ui-system/typography/text',
		'ui-system/typography/heading',
		'ui-system/form/buttons/button',
		'ui-system/blocks/setting-selector',
		'ui-system/blocks/chips/chip-filter',
		'ui-system/blocks/status-block',

		'statemanager/redux/store',
		'statemanager/redux/connect',

		'calendar:layout/icons',
		'calendar:layout/dialog/dialog-sharing',
		'calendar:layout/menu/recursion-mode',
		'calendar:sharing',
		'calendar:data-managers/event-manager',
		'calendar:data-managers/section-manager',
		'calendar:data-managers/location-manager',
		'calendar:data-managers/settings-manager',
		'calendar:data-managers/sync-manager',
		'calendar:data-managers/collab-manager',
		'calendar:data-managers/user-manager',
		'calendar:date-helper',
		'calendar:aha-moments-manager',
		'calendar:event-edit-form',
		'calendar:event-view-form',
		'calendar:statemanager/redux/slices/events',
		'calendar:enums',
	],
	'bundle' => [
		'./src/state',
		'./src/layout',
		'./src/layout/day-label',
		'./src/layout/event',
		'./src/layout/calendar-grid',
		'./src/layout/invites-banner',
		'./src/layout/search-header',
		'./src/layout/event-list',
		'./src/layout/event-list-view',
		'./src/more-menu',
		'./src/sharing-button',
		'./src/settings-page',
		'./src/list-skeleton',
		'./src/search/layout',
		'./src/search/preset',
	],
];
