
CREATE TABLE b_stafftrack_shift (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL,
	SHIFT_DATE date NOT NULL,
	DATE_CREATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	STATUS smallint NOT NULL,
	LOCATION text,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_stafftrack_shift_user_id ON b_stafftrack_shift (user_id);
CREATE INDEX ix_b_stafftrack_shift_shift_date ON b_stafftrack_shift (shift_date);
CREATE INDEX ix_b_stafftrack_shift_status ON b_stafftrack_shift (status);

CREATE TABLE b_stafftrack_shift_geo (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SHIFT_ID int NOT NULL,
	IMAGE_URL text NOT NULL,
	ADDRESS text NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_stafftrack_shift_geo_shift_id ON b_stafftrack_shift_geo (shift_id);

CREATE TABLE b_stafftrack_shift_cancellation (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SHIFT_ID int NOT NULL,
	REASON text NOT NULL,
	DATE_CANCEL timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_stafftrack_shift_cancellation_shift_id ON b_stafftrack_shift_cancellation (shift_id);

CREATE TABLE b_stafftrack_option (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL,
	NAME varchar(255) NOT NULL,
	VALUE varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_stafftrack_option_user_id_name ON b_stafftrack_option (user_id, name);

CREATE TABLE b_stafftrack_counter (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL,
	MUTE_STATUS smallint NOT NULL DEFAULT 0,
	MUTE_UNTIL timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_stafftrack_counter_user_id ON b_stafftrack_counter (user_id);

CREATE TABLE b_stafftrack_handled_chat (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CHAT_ID int NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_stafftrack_handled_chat_chat_id ON b_stafftrack_handled_chat (chat_id);

CREATE TABLE b_stafftrack_user_statistics_hash (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	USER_ID int NOT NULL,
	HASH varchar(64) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_stafftrack_user_statistics_hash_user_id ON b_stafftrack_user_statistics_hash (user_id);

create table if not exists b_stafftrack_shift_message (
	ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	SHIFT_ID int NOT NULL,
	MESSAGE_ID int NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX ix_b_stafftrack_shift_message_shift_id on b_stafftrack_shift_message (shift_id);

