CREATE TABLE b_dav_locks (
      ID varchar(128) NOT NULL,
      PATH varchar(255) NOT NULL,
      EXPIRES int NOT NULL,
      LOCK_OWNER varchar(255),
      LOCK_DEPTH char(1) NOT NULL DEFAULT 'N',
      LOCK_TYPE char(1) NOT NULL DEFAULT 'R',
      LOCK_SCOPE char(1) NOT NULL DEFAULT 'S',
      CREATED timestamp NOT NULL,
      MODIFIED timestamp NOT NULL,
      PRIMARY KEY (ID)
);
CREATE INDEX ix_b_dav_locks_path ON b_dav_locks (path);
CREATE INDEX ix_b_dav_locks_expires ON b_dav_locks (expires);

CREATE TABLE b_dav_connections (
      ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      ENTITY_TYPE varchar(32) NOT NULL DEFAULT 'user',
      ENTITY_ID int NOT NULL,
      ACCOUNT_TYPE varchar(32) NOT NULL,
      SYNC_TOKEN varchar(128),
      NAME varchar(128) NOT NULL,
      SERVER_SCHEME varchar(5) NOT NULL DEFAULT 'http',
      SERVER_HOST varchar(128) NOT NULL,
      SERVER_PORT int NOT NULL DEFAULT 80,
      SERVER_USERNAME varchar(128),
      SERVER_PASSWORD varchar(128),
      SERVER_PATH varchar(255) NOT NULL DEFAULT '/',
      CREATED timestamp NOT NULL,
      MODIFIED timestamp NOT NULL,
      SYNCHRONIZED timestamp,
      LAST_RESULT varchar(128),
      IS_DELETED varchar(1) NOT NULL DEFAULT 'N',
      NEXT_SYNC_TRY timestamp DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (ID)
);
CREATE INDEX ix_b_dav_connections_account_type ON b_dav_connections (account_type);
CREATE INDEX ix_b_dav_connections_entity_type_entity_id_account_type ON b_dav_connections (entity_type, entity_id, account_type);

CREATE TABLE b_dav_tokens (
      TOKEN varchar(45),
      USER_ID int NOT NULL,
      EXPIRED_AT timestamp NOT NULL,
      PRIMARY KEY (TOKEN)
);