export type ResourceDto = {
	id: number | null,
	type: {
		id: number,
	},
	name: string,
	description: string | null,
	isMain: boolean,
	slotRanges: [{
		id: number | null,
		from: number,
		to: number,
		weekDays: string[],
		slotSize: number,
	}],
	counter: number | null,
	isConfirmationNotificationOn: boolean,
	isFeedbackNotificationOn: boolean,
	isInfoNotificationOn: boolean,
	isDelayedNotificationOn: boolean,
	isReminderNotificationOn: boolean,
	templateTypeConfirmation: string,
	templateTypeFeedback: string,
	templateTypeInfo: string,
	templateTypeDelayed: string,
	templateTypeReminder: string,
	createdBy: number | null,
	createdAt: number | null,
	updatedAt: number | null,
};
