
CREATE TABLE IF NOT EXISTS b_voximplant_phone (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  USER_ID int NOT NULL,
  PHONE_NUMBER varchar(20) NOT NULL,
  PHONE_MNEMONIC varchar(20),
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_phone_user_id_phone_number ON b_voximplant_phone (user_id, phone_number);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_phone_phone_number ON b_voximplant_phone (phone_number);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_voximplant_phone_user_id_phone_mnemonic ON b_voximplant_phone (user_id, phone_mnemonic);

CREATE TABLE IF NOT EXISTS b_voximplant_statistic (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ACCOUNT_ID int,
  APPLICATION_ID int,
  APPLICATION_NAME varchar(80),
  PORTAL_USER_ID int,
  PORTAL_NUMBER varchar(50),
  PHONE_NUMBER varchar(20) NOT NULL,
  INCOMING varchar(50) NOT NULL DEFAULT '1',
  SESSION_ID int8,
  CALL_ID varchar(255) NOT NULL,
  EXTERNAL_CALL_ID varchar(64),
  CALL_CATEGORY varchar(20) DEFAULT 'external',
  CALL_LOG varchar(2000),
  CALL_DIRECTION varchar(255),
  CALL_DURATION int NOT NULL DEFAULT 0,
  CALL_START_DATE timestamp NOT NULL,
  CALL_STATUS int DEFAULT 0,
  CALL_FAILED_CODE varchar(255),
  CALL_FAILED_REASON varchar(255),
  CALL_RECORD_ID int,
  CALL_RECORD_URL varchar(2000),
  CALL_WEBDAV_ID int,
  CALL_VOTE smallint DEFAULT 0,
  COST double precision DEFAULT 0,
  COST_CURRENCY varchar(50),
  CRM_ENTITY_TYPE varchar(50),
  CRM_ENTITY_ID int,
  CRM_ACTIVITY_ID int,
  REST_APP_ID int,
  REST_APP_NAME varchar(255),
  TRANSCRIPT_PENDING char(1),
  TRANSCRIPT_ID int,
  REDIAL_ATTEMPT int,
  COMMENT text,
  RECORD_DURATION int,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_start_date ON b_voximplant_statistic (call_start_date);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_failed_code ON b_voximplant_statistic (call_failed_code);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_category ON b_voximplant_statistic (call_category);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_vote ON b_voximplant_statistic (call_vote);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_id ON b_voximplant_statistic (call_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_start_date_call_category_call_du ON b_voximplant_statistic (call_start_date, call_category, call_duration, cost);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_external_call_id ON b_voximplant_statistic (external_call_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_portal_user_id_call_start_date ON b_voximplant_statistic (portal_user_id, call_start_date);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_crm_activity_id ON b_voximplant_statistic (crm_activity_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_record_id ON b_voximplant_statistic (call_record_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_call_webdav_id ON b_voximplant_statistic (call_webdav_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_crm_entity_id_crm_entity_type ON b_voximplant_statistic (crm_entity_id, crm_entity_type);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_session_id ON b_voximplant_statistic (session_id);
CREATE INDEX IF NOT EXISTS tx_b_voximplant_statistic_comment ON b_voximplant_statistic USING GIN (to_tsvector('english', comment));

CREATE TABLE IF NOT EXISTS b_voximplant_statistic_index (
  STATISTIC_ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONTENT text,
  PRIMARY KEY (STATISTIC_ID)
);
CREATE INDEX IF NOT EXISTS tx_b_voximplant_statistic_index_content ON b_voximplant_statistic_index USING GIN (to_tsvector('english', content));

CREATE TABLE IF NOT EXISTS b_voximplant_statistic_missed (
  ID int NOT NULL,
  CALL_START_DATE timestamp NOT NULL,
  PHONE_NUMBER varchar(20) NOT NULL,
  PORTAL_USER_ID int,
  CALLBACK_ID int,
  CALLBACK_CALL_START_DATE timestamp,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_missed_phone_number ON b_voximplant_statistic_missed (phone_number);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_statistic_missed_callback_id ON b_voximplant_statistic_missed (callback_id);

CREATE TABLE IF NOT EXISTS b_voximplant_call (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONFIG_ID int,
  USER_ID int,
  PORTAL_USER_ID int,
  CALL_ID varchar(255) NOT NULL,
  EXTERNAL_CALL_ID varchar(64),
  SESSION_ID int8,
  INCOMING varchar(50),
  CALLER_ID varchar(255),
  STATUS varchar(50),
  CRM char(1) NOT NULL DEFAULT 'Y',
  CRM_ACTIVITY_ID int,
  CRM_CALL_LIST int,
  CRM_BINDINGS text,
  ACCESS_URL varchar(255),
  DATE_CREATE timestamp,
  REST_APP_ID int,
  EXTERNAL_LINE_ID int,
  PORTAL_NUMBER varchar(255),
  STAGE varchar(50),
  IVR_ACTION_ID int,
  QUEUE_ID int,
  QUEUE_HISTORY text,
  CALLBACK_PARAMETERS text,
  COMMENT text,
  WORKTIME_SKIPPED char(1) NOT NULL DEFAULT 'N',
  SIP_HEADERS text,
  GATHERED_DIGITS varchar(15),
  PARENT_CALL_ID varchar(255),
  LAST_PING timestamp,
  EXECUTION_GRAPH text,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_call_id ON b_voximplant_call (call_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_date_create_status ON b_voximplant_call (date_create, status);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_session_id ON b_voximplant_call (session_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_parent_call_id ON b_voximplant_call (parent_call_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_external_call_id ON b_voximplant_call (external_call_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_status_last_ping ON b_voximplant_call (status, last_ping);

CREATE TABLE IF NOT EXISTS b_voximplant_call_user (
  CALL_ID varchar(255) NOT NULL,
  USER_ID int NOT NULL,
  ROLE varchar(50),
  STATUS varchar(50),
  DEVICE varchar(50),
  INSERTED timestamp,
  PRIMARY KEY (CALL_ID, USER_ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_user_call_id_user_id_role_status ON b_voximplant_call_user (call_id, user_id, role, status);

CREATE TABLE IF NOT EXISTS b_voximplant_call_crm_entity (
  CALL_ID varchar(255) NOT NULL,
  ENTITY_TYPE varchar(50) NOT NULL,
  ENTITY_ID int NOT NULL,
  IS_PRIMARY char(1) NOT NULL DEFAULT 'N',
  IS_CREATED char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (CALL_ID, ENTITY_TYPE, ENTITY_ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_call_crm_entity_entity_id_entity_type ON b_voximplant_call_crm_entity (entity_id, entity_type);

CREATE TABLE IF NOT EXISTS b_voximplant_sip (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  APP_ID varchar(128),
  CONFIG_ID int NOT NULL,
  TYPE varchar(255) DEFAULT 'office',
  REG_ID int DEFAULT 0,
  SERVER varchar(255),
  LOGIN varchar(255),
  PASSWORD varchar(255),
  INCOMING_SERVER varchar(255),
  INCOMING_LOGIN varchar(255),
  INCOMING_PASSWORD varchar(255),
  AUTH_USER varchar(255),
  OUTBOUND_PROXY varchar(255),
  DETECT_LINE_NUMBER char(1) NOT NULL DEFAULT 'N',
  LINE_DETECT_HEADER_ORDER varchar(32) NOT NULL DEFAULT 'diversion;to',
  REGISTRATION_STATUS_CODE int,
  REGISTRATION_ERROR_MESSAGE text DEFAULT null,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_sip_config_id ON b_voximplant_sip (config_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_sip_app_id ON b_voximplant_sip (app_id);

CREATE TABLE IF NOT EXISTS b_voximplant_external_line (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  TYPE varchar(16) NOT NULL DEFAULT 'rest-app',
  NUMBER varchar(50) NOT NULL,
  NORMALIZED_NUMBER varchar(50) NOT NULL,
  NAME varchar(255),
  REST_APP_ID int,
  SIP_ID int,
  IS_MANUAL char(1) NOT NULL DEFAULT 'N',
  CRM_AUTO_CREATE char(1) NOT NULL DEFAULT 'Y',
  DATE_CREATE timestamp,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_voximplant_external_line_rest_app_id_number ON b_voximplant_external_line (rest_app_id, number);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_voximplant_external_line_sip_id_normalized_number_type ON b_voximplant_external_line (sip_id, normalized_number, type);

CREATE TABLE IF NOT EXISTS b_voximplant_number (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NUMBER varchar(50) NOT NULL,
  NAME varchar(255),
  COUNTRY_CODE varchar(50),
  VERIFIED char(1) DEFAULT 'Y',
  DATE_CREATE timestamp,
  SUBSCRIPTION_ID int,
  CONFIG_ID int,
  TO_DELETE char(1) DEFAULT 'N',
  DATE_DELETE timestamp,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_voximplant_number_number ON b_voximplant_number (number);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_number_config_id ON b_voximplant_number (config_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_number_to_delete_date_delete ON b_voximplant_number (to_delete, date_delete);

CREATE TABLE IF NOT EXISTS b_voximplant_caller_id (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NUMBER varchar(50) NOT NULL,
  VERIFIED char(1) DEFAULT 'N',
  DATE_CREATE timestamp,
  VERIFIED_UNTIL date,
  CONFIG_ID int,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_voximplant_caller_id_number ON b_voximplant_caller_id (number);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_caller_id_config_id ON b_voximplant_caller_id (config_id);

CREATE TABLE IF NOT EXISTS b_voximplant_config (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PORTAL_MODE varchar(50),
  SEARCH_ID varchar(255),
  PHONE_NAME varchar(255),
  PHONE_COUNTRY_CODE varchar(50),
  PHONE_VERIFIED char(1) DEFAULT 'Y',
  CRM char(1) NOT NULL DEFAULT 'Y',
  CRM_RULE varchar(50),
  CRM_CREATE varchar(50) DEFAULT 'none',
  CRM_CREATE_CALL_TYPE varchar(30) DEFAULT 'all',
  CRM_SOURCE varchar(50) DEFAULT 'CALL',
  CRM_FORWARD char(1) NOT NULL DEFAULT 'Y',
  CRM_TRANSFER_CHANGE char(1) DEFAULT 'N',
  IVR char(1) NOT NULL DEFAULT 'N',
  QUEUE_ID int,
  IVR_ID int,
  DIRECT_CODE char(1) NOT NULL DEFAULT 'Y',
  DIRECT_CODE_RULE varchar(50),
  RECORDING char(1) NOT NULL DEFAULT 'Y',
  RECORDING_NOTICE char(1) DEFAULT 'N',
  RECORDING_TIME smallint DEFAULT 0,
  RECORDING_STEREO char(1) DEFAULT 'N',
  VOTE char(1) DEFAULT 'N',
  FORWARD_LINE varchar(255) DEFAULT 'default',
  TIMEMAN char(1) NOT NULL DEFAULT 'N',
  VOICEMAIL char(1) NOT NULL DEFAULT 'Y',
  MELODY_LANG char(2) NOT NULL DEFAULT 'EN',
  MELODY_WELCOME int,
  MELODY_WELCOME_ENABLE char(1) NOT NULL DEFAULT 'Y',
  MELODY_VOICEMAIL int,
  MELODY_WAIT int,
  MELODY_ENQUEUE int,
  MELODY_HOLD int,
  MELODY_RECORDING int,
  MELODY_VOTE int,
  MELODY_VOTE_END int,
  WORKTIME_ENABLE char(1) DEFAULT 'N',
  WORKTIME_FROM varchar(5),
  WORKTIME_TO varchar(5),
  WORKTIME_TIMEZONE varchar(50),
  WORKTIME_HOLIDAYS varchar(2000),
  WORKTIME_DAYOFF varchar(20),
  WORKTIME_DAYOFF_RULE varchar(50) DEFAULT 'voicemail',
  WORKTIME_DAYOFF_NUMBER varchar(20),
  WORKTIME_DAYOFF_MELODY int,
  WAIT_CRM int NOT NULL DEFAULT 30,
  WAIT_DIRECT int NOT NULL DEFAULT 30,
  USE_SIP_TO char(1) DEFAULT 'N',
  TRANSCRIBE char(1) DEFAULT 'N',
  TRANSCRIBE_LANG char(15),
  TRANSCRIBE_PROVIDER varchar(25),
  CALLBACK_REDIAL char(1) DEFAULT 'N',
  CALLBACK_REDIAL_ATTEMPTS int,
  CALLBACK_REDIAL_PERIOD int,
  LINE_PREFIX char(10),
  CAN_BE_SELECTED char(1) DEFAULT 'N',
  BACKUP_NUMBER varchar(255),
  BACKUP_LINE varchar(255),
  REDIRECT_WITH_CLIENT_NUMBER char(1) DEFAULT 'N',
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_config_search_id ON b_voximplant_config (search_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_config_portal_mode ON b_voximplant_config (portal_mode);

CREATE TABLE IF NOT EXISTS b_voximplant_line_access (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONFIG_ID int,
  LINE_SEARCH_ID varchar(255),
  ACCESS_CODE varchar(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_voximplant_queue (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NAME varchar(255),
  TYPE varchar(50) DEFAULT 'evenly',
  WAIT_TIME smallint DEFAULT 0,
  NO_ANSWER_RULE varchar(50) DEFAULT 'voicemail',
  NEXT_QUEUE_ID int,
  FORWARD_NUMBER varchar(20),
  PHONE_NUMBER varchar(20),
  ALLOW_INTERCEPT char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_voximplant_queue_user (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  QUEUE_ID int NOT NULL,
  USER_ID int NOT NULL,
  STATUS varchar(50),
  LAST_ACTIVITY_DATE timestamp,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_queue_user_user_id ON b_voximplant_queue_user (user_id);

CREATE TABLE IF NOT EXISTS b_voximplant_blacklist (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PHONE_NUMBER varchar(20),
  NUMBER_STRIPPED varchar(20),
  NUMBER_E164 varchar(20),
  INSERTED timestamp,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_blacklist_phone_number ON b_voximplant_blacklist (phone_number);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_blacklist_number_e164 ON b_voximplant_blacklist (number_e164);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_blacklist_number_stripped ON b_voximplant_blacklist (number_stripped);

CREATE TABLE IF NOT EXISTS b_voximplant_role (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NAME varchar(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_voximplant_role_permission (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ROLE_ID int NOT NULL,
  ENTITY varchar(50) NOT NULL,
  ACTION varchar(50) NOT NULL,
  PERMISSION char(1),
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_role_permission_role_id ON b_voximplant_role_permission (role_id);

CREATE TABLE IF NOT EXISTS b_voximplant_role_access (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ROLE_ID int NOT NULL,
  ACCESS_CODE varchar(100) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_role_access_role_id ON b_voximplant_role_access (role_id);

CREATE TABLE IF NOT EXISTS b_voximplant_ivr (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  NAME varchar(255) NOT NULL,
  FIRST_ITEM_ID int,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_voximplant_ivr_item (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CODE varchar(50),
  IVR_ID int,
  NAME varchar(255),
  TYPE varchar(10) NOT NULL DEFAULT 'message',
  URL varchar(2000),
  MESSAGE text,
  FILE_ID int,
  TIMEOUT int NOT NULL DEFAULT 15,
  TIMEOUT_ACTION varchar(255) NOT NULL DEFAULT 'exit',
  TTS_VOICE varchar(50),
  TTS_SPEED varchar(20),
  TTS_VOLUME varchar(20),
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_voximplant_ivr_item_ivr_id_code ON b_voximplant_ivr_item (ivr_id, code);

CREATE TABLE IF NOT EXISTS b_voximplant_ivr_action (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ITEM_ID int NOT NULL,
  DIGIT char(1),
  ACTION varchar(255) NOT NULL,
  PARAMETERS text,
  LEAD_FIELDS text,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_voximplant_transcript (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  SESSION_ID int8,
  CALL_ID varchar(255),
  URL varchar(255),
  CONTENT text,
  COST double precision DEFAULT 0,
  COST_CURRENCY varchar(50),
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_transcript_session_id ON b_voximplant_transcript (session_id);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_transcript_call_id ON b_voximplant_transcript (call_id);

CREATE TABLE IF NOT EXISTS b_voximplant_transcript_line (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  TRANSCRIPT_ID int NOT NULL,
  SIDE varchar(10) NOT NULL,
  START_TIME int NOT NULL,
  STOP_TIME int NOT NULL,
  MESSAGE text,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_voximplant_transcript_line_transcript_id ON b_voximplant_transcript_line (transcript_id);
CREATE INDEX IF NOT EXISTS tx_b_voximplant_transcript_line_message ON b_voximplant_transcript_line USING GIN (to_tsvector('english', message));
