CREATE TABLE IF NOT EXISTS b_sign_blank (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  TITLE varchar(255) NOT NULL,
  EXTERNAL_ID int DEFAULT null,
  HOST varchar(255) DEFAULT null,
  FILE_ID text NOT NULL,
  STATUS text,
  CONVERTED char(1) NOT NULL DEFAULT 'N',
  SCENARIO smallint NOT NULL DEFAULT 0,
  CREATED_BY_ID int NOT NULL,
  MODIFIED_BY_ID int NOT NULL,
  DATE_CREATE timestamp DEFAULT CURRENT_TIMESTAMP,
  DATE_MODIFY timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOR_TEMPLATE SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_blank_external_id_host ON b_sign_blank (external_id, host);

CREATE TABLE IF NOT EXISTS b_sign_document (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  TITLE varchar(255) DEFAULT null,
  HASH char(19) DEFAULT null,
  SEC_CODE char(20) DEFAULT null,
  HOST varchar(255) DEFAULT null,
  BLANK_ID int NOT NULL,
  SCENARIO smallint NULL,
  UID varchar(20),
  STATUS varchar(10),
  ENTITY_TYPE varchar(20) NOT NULL,
  ENTITY_ID int NOT NULL,
  META text DEFAULT null,
  PROCESSING_STATUS char(1) NOT NULL DEFAULT 'B',
  PROCESSING_ERROR text DEFAULT null,
  LANG_ID char(2) DEFAULT null,
  RESULT_FILE_ID int DEFAULT null,
  VERSION smallint DEFAULT 1,
  CREATED_BY_ID int NOT NULL,
  MODIFIED_BY_ID int NOT NULL,
  GROUP_ID int8 DEFAULT null,
  DATE_CREATE timestamp DEFAULT CURRENT_TIMESTAMP,
  DATE_MODIFY timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DATE_SIGN timestamp NULL DEFAULT NULL,
  COMPANY_UID varchar(32) DEFAULT null,
  REPRESENTATIVE_ID int DEFAULT null,
  PARTIES int NOT NULL DEFAULT 2,
  EXTERNAL_ID varchar(255) DEFAULT null,
  SCHEME smallint DEFAULT 0,
  REGION_DOCUMENT_TYPE varchar(255) DEFAULT null,
  STOPPED_BY_ID int DEFAULT null,
  EXTERNAL_DATE_CREATE timestamp DEFAULT null,
  PROVIDER_CODE varchar(255) DEFAULT null,
  TEMPLATE_ID int8 DEFAULT null,
  CHAT_ID int DEFAULT null,
  CREATED_FROM_DOCUMENT_ID int DEFAULT null,
  INITIATED_BY_TYPE smallint DEFAULT 0,
  HCMLINK_COMPANY_ID int null default null,
  DATE_STATUS_CHANGED timestamp DEFAULT null,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_entity_type_entity_id ON b_sign_document (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_host ON b_sign_document (host);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_uid ON b_sign_document (uid);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_company_uid ON b_sign_document (company_uid);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_blank_id ON b_sign_document (blank_id);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_group_id ON b_sign_document (group_id);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_created_by_id ON b_sign_document (created_by_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_sign_document_hash ON b_sign_document (hash);

CREATE TABLE IF NOT EXISTS b_sign_member (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  DOCUMENT_ID int8 NOT NULL,
  CONTACT_ID int8 NOT NULL,
  PART int NOT NULL,
  HASH char(32) NOT NULL,
  SIGNED char(1) NOT NULL DEFAULT 'N',
  VERIFIED char(1) NOT NULL DEFAULT 'N',
  MUTE char(1) NOT NULL DEFAULT 'N',
  COMMUNICATION_TYPE varchar(20),
  COMMUNICATION_VALUE varchar(100),
  USER_DATA text,
  META text DEFAULT null,
  SIGNATURE_FILE_ID int DEFAULT null,
  STAMP_FILE_ID int DEFAULT null,
  CREATED_BY_ID int NOT NULL,
  MODIFIED_BY_ID int NOT NULL,
  DATE_CREATE timestamp DEFAULT CURRENT_TIMESTAMP,
  DATE_MODIFY timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DATE_SIGN timestamp NULL DEFAULT NULL,
  DATE_DOC_DOWNLOAD timestamp NULL DEFAULT NULL,
  DATE_DOC_VERIFY timestamp NULL DEFAULT NULL,
  IP varchar(15),
  TIME_ZONE_NAME varchar(50),
  TIME_ZONE_OFFSET int,
  ENTITY_ID int8,
  ENTITY_TYPE varchar(20),
  PRESET_ID int8,
  ROLE smallint DEFAULT null,
  CONFIGURED smallint NULL DEFAULT NULL,
  REMINDER_TYPE smallint default 0,
  REMINDER_LAST_SEND_DATE timestamp null default null,
  REMINDER_PLANNED_NEXT_SEND_DATE timestamp null default null,
  REMINDER_COMPLETED smallint default 0,
  REMINDER_START_DATE timestamp null default null,
  EMPLOYEE_ID int null default null,
  HCMLINK_JOB_ID int8 null default null,
  DATE_SEND timestamp DEFAULT null,
  DATE_STATUS_CHANGED timestamp null default null,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_member_document_id ON b_sign_member (document_id);
CREATE INDEX IF NOT EXISTS ix_b_sign_member_hash ON b_sign_member (hash);

CREATE TABLE IF NOT EXISTS b_sign_block (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CODE varchar(50) NOT NULL,
  TYPE varchar(20),
  BLANK_ID int NOT NULL,
  BLANK_POSITION text NOT NULL,
  BLANK_STYLE text DEFAULT null,
  BLANK_DATA text NOT NULL,
  PART int NOT NULL,
  CREATED_BY_ID int NOT NULL,
  MODIFIED_BY_ID int NOT NULL,
  DATE_CREATE timestamp DEFAULT CURRENT_TIMESTAMP,
  DATE_MODIFY timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ROLE smallint DEFAULT null,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_block_blank_id ON b_sign_block (blank_id);
CREATE INDEX IF NOT EXISTS ix_b_sign_block_blank_id_part ON b_sign_block (blank_id, part);

CREATE TABLE IF NOT EXISTS b_sign_integration_form (
  ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  BLANK_ID int NOT NULL,
  PART int NOT NULL,
  FORM_ID int NOT NULL,
  CREATED_BY_ID int NOT NULL,
  MODIFIED_BY_ID int NOT NULL,
  DATE_CREATE timestamp DEFAULT CURRENT_TIMESTAMP,
  DATE_MODIFY timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_integration_form_blank_id_part ON b_sign_integration_form (blank_id, part);

CREATE TABLE IF NOT EXISTS b_sign_documentgenerator_blank (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  BLANK_ID int8 NOT NULL,
  DOCUMENT_GENERATOR_TEMPLATE_ID int8 NOT NULL,
  INITIATOR varchar(1024),
  CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_sign_permission (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ROLE_ID int8 NOT NULL,
  PERMISSION_ID varchar(32) NOT NULL DEFAULT '',
  VALUE varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (ID),
  UNIQUE (ROLE_ID, PERMISSION_ID)
);

CREATE TABLE IF NOT EXISTS b_sign_service_user (
  USER_ID int8 NOT NULL,
  UID varchar(32) NOT NULL,
  DATE_CREATE timestamp NOT NULL,
  PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_sign_service_user_uid ON b_sign_service_user (uid);

CREATE TABLE IF NOT EXISTS b_sign_file (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ENTITY_TYPE_ID smallint NOT NULL,
  ENTITY_ID int8 NOT NULL,
  CODE smallint NOT NULL,
  FILE_ID int8 NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_b_sign_file_entity_id_entity_type_id_code ON b_sign_file (entity_id, entity_type_id, code);

CREATE TABLE IF NOT EXISTS b_sign_blank_resource (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  BLANK_ID int NOT NULL,
  FILE_ID int NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_sign_legal_log (
  ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  DOCUMENT_ID int8 NOT NULL,
  DOCUMENT_UID varchar(20) NOT NULL,
  MEMBER_ID int8 DEFAULT NULL,
  MEMBER_UID varchar(32) DEFAULT NULL,
  CODE varchar(50) NOT NULL,
  DESCRIPTION text NOT NULL,
  USER_ID int8 DEFAULT NULL,
  DATE_CREATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_legal_log_document_id ON b_sign_legal_log (document_id);

CREATE TABLE IF NOT EXISTS b_sign_document_required_field
(
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	DOCUMENT_ID int8 NOT NULL,
	TYPE varchar(20) NOT NULL,
	ROLE smallint NOT NULL,
	PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_document_required_field_document_id ON b_sign_document_required_field (document_id);

CREATE TABLE IF NOT EXISTS b_sign_document_chat
(
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CHAT_ID int8 NOT NULL,
	DOCUMENT_ID int8 NOT NULL,
	TYPE smallint NOT NULL,
	PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS ix_b_sign_document_chat_document_id ON b_sign_document_chat (document_id);

CREATE TABLE IF NOT EXISTS b_sign_document_template (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	UID varchar(32) NOT NULL,
	TITLE varchar(255) NOT NULL,
	STATUS smallint NOT NULL,
	CREATED_BY_ID int NOT NULL,
	MODIFIED_BY_ID int NULL,
	DATE_CREATE timestamp NOT NULL,
	DATE_MODIFY timestamp DEFAULT NULL,
	VISIBILITY smallint NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_b_sign_document_template_uid ON b_sign_document_template (uid);

CREATE TABLE IF NOT EXISTS b_sign_document_group (
	 ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	 CREATED_BY_ID int NOT NULL,
	 DATE_CREATE timestamp NOT NULL,
	 DATE_MODIFY timestamp DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS b_sign_node_sync
(
	ID bigint generated by default as identity not null,
	DOCUMENT_ID int not null,
	NODE_ID bigint not null,
	IS_FLAT smallint not null,
	STATUS smallint not null,
	PAGE int not null,
	DATE_CREATE timestamp,
	DATE_MODIFY timestamp,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_b_sign_node_sync_document_node ON b_sign_node_sync (document_id, node_id, is_flat);
CREATE INDEX IF NOT EXISTS ix_b_sign_node_sync_document_status ON b_sign_node_sync (document_id, status);

CREATE TABLE IF NOT EXISTS b_sign_member_node
(
	MEMBER_ID bigint not null,
	NODE_SYNC_ID bigint not null,
	USER_ID bigint not null,
	DOCUMENT_ID int not null,
	DATE_CREATE timestamp,
	PRIMARY KEY (MEMBER_ID, NODE_SYNC_ID)
);
CREATE INDEX IF NOT EXISTS ix_b_sign_member_node_document_node ON b_sign_member_node (document_id, node_sync_id);

CREATE TABLE IF NOT EXISTS b_sign_field_value (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	MEMBER_ID int8 not null,
	FIELD_NAME varchar(255) NOT NULL,
	VALUE text NOT NULL,
	DATE_CREATE timestamp NOT NULL,
	DATE_MODIFY timestamp DEFAULT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_b_sign_field_value_member_id_field_name ON b_sign_field_value (member_id, field_name);
