<?php

return [
	'extensions' => [
		//'im:messenger/lib/dev/action-timer',
		'im:messenger/component/messenger-base',
		'type',
		'loc',
		'entity-ready',
		'utils/object',
		'list/selector',
		'pull/client/events',
		'statemanager/vuex',
		'statemanager/vuex-manager',
		'im:chat/timer',
		'im:chat/selector/adapter/dialog-list',
		'im:messenger/core/copilot',
		'im:messenger/const',
		'im:messenger/lib/helper',
		'im:messenger/lib/params',
		'im:messenger/controller/recent/copilot',
		'im:messenger/controller/dialog/copilot',
		'im:messenger/controller/dialog/lib/assets',
		'im:messenger/controller/chat-creator',
		'im:messenger/controller/forward-selector',
		'im:messenger/controller/dialog-creator',
		'im:messenger/controller/sidebar',
		'im:messenger/view/recent',
		'im:messenger/lib/logger',
		'im:messenger/lib/counters',
		'im:messenger/model',
		'im:messenger/view/dialog',
		'im:messenger/provider/pull/chat',
		'im:messenger/provider/pull/copilot',
		'im:messenger/provider/pull/plan-limits',
		'im:messenger/provider/service',
		'im:messenger/provider/data',
		'im:messenger/lib/rest-manager',
		'im:messenger/lib/integration/mobile/communication',
		'im:messenger/lib/promotion',
		'im:messenger/lib/notifier',
		'im:messenger/lib/emitter',
		'im:messenger/lib/visibility-manager',
		'im:messenger/lib/ui/header/icon',
		'im:messenger/widgets/user-profile',
		'im:messenger/widgets/participants-list',
		'im:messenger/lib/ui/header',
		'im:messenger/controller/search/experimental',
		'im:messenger/lib/feature',
		'im:messenger/lib/smile-manager',
		'im:messenger/lib/di/service-locator',
	],
	'components' => [],
	//'packer' => [],
];