<?
$DB->Query("DELETE FROM b_event_type WHERE EVENT_NAME in ('IMOL_HISTORY_LOG', 'IMOL_OPERATOR_ANSWER')");
$DB->Query("DELETE FROM b_event_message WHERE EVENT_NAME in ('IMOL_HISTORY_LOG', 'IMOL_OPERATOR_ANSWER')");
?>