CREATE TABLE b_transformer_command (
	ID int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	GUID varchar(32) NOT NULL,
	STATUS int8 NOT NULL DEFAULT 10,
	COMMAND varchar(255) NOT NULL,
	MODULE text NOT NULL,
	CALLBACK text NOT NULL,
	PARAMS text NOT NULL,
	FILE varchar(255),
	ERROR text,
	ERROR_CODE int,
	UPDATE_TIME timestamp,
	SEND_TIME timestamp,
	CONTROLLER_URL varchar(255),
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX ux_b_transformer_command_guid ON b_transformer_command (guid);
CREATE INDEX ix_b_transformer_command_file ON b_transformer_command (file);
CREATE INDEX ix_b_transformer_command_update_time_error ON b_transformer_command (update_time, error);
