<?php

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}

return [
	'css' => 'dist/booking.bundle.css',
	'js' => 'dist/booking.bundle.js',
	'rel' => [
		'booking.component.mixin.loc-mixin',
		'main.loader',
		'booking.provider.service.main-page-service',
		'booking.provider.service.dictionary-service',
		'booking.provider.service.calendar-service',
		'booking.lib.mouse-position',
		'main.core.events',
		'ui.counterpanel',
		'ui.cnt',
		'booking.component.counter',
		'booking.component.time-selector',
		'booking.component.popup-maker',
		'ui.vue3.directives.lazyload',
		'main.sidepanel',
		'ui.notification-manager',
		'booking.provider.service.booking-actions-service',
		'booking.component.loader',
		'ui.vue3.directives.hint',
		'ui.icon-set.main',
		'booking.component.popup',
		'booking.lib.range',
		'booking.core',
		'ui.date-picker',
		'booking.lib.currency-format',
		'booking.component.statistics-popup',
		'ui.dialogs.messagebox',
		'ui.hint',
		'booking.provider.service.resources-service',
		'ui.icon-set.actions',
		'booking.resource-creation-wizard',
		'booking.provider.service.resource-dialog-service',
		'booking.lib.resources',
		'booking.lib.resources-date-cache',
		'main.popup',
		'ui.icon-set.api.core',
		'ui.icon-set.api.vue',
		'booking.provider.service.option-service',
		'booking.lib.help-desk',
		'ui.entity-selector',
		'booking.lib.limit',
		'booking.provider.service.booking-service',
		'ui.ears',
		'main.date',
		'booking.lib.duration',
		'booking.component.client-popup',
		'booking.component.button',
		'ui.auto-launch',
		'ui.vue3.vuex',
		'main.core',
		'ui.vue3',
		'ui.banner-dispatcher',
		'booking.lib.resolvable',
		'booking.const',
		'booking.lib.aha-moments',
	],
	'skip_core' => false,
];
