<?php

return [
	'extensions' => [
		'im:messenger/const',
		'im:messenger/lib/helper',
		'im:messenger/controller/recent',
		'im:messenger/controller/dialog',
		'im:messenger/controller/dialog-selector',
		'im:messenger/controller/chat-creator',
		'im:messenger/view/recent',
		'im:messenger/lib/logger',
		'im:messenger/lib/counters',
		'im:messenger/model',
		'im:messenger/view/dialog',
		'im:messenger/pull-handler',
		'im:messenger/push-handler',
		'im:messenger/lib/rest-manager',
		'im:messenger/lib/integration/mobile/communication',
		'im:messenger/lib/promotion',
		'im:messenger/lib/notifier',
		'im:messenger/lib/event',
		'im:chat/timer',
		'im:chat/selector/adapter/dialog-list',
		'list/selector',
		'pull/client/events',
		'statemanager/vuex',
		'statemanager/vuex-manager',
		'entity-ready',
		'type',
		'loc',
	],
	'components' => [],
];