<?php

return [
	'extensions' => [
		'im:messenger/core',
		'im:messenger/const',
		'im:messenger/lib/helper',
		'im:messenger/controller/recent',
		'im:messenger/controller/dialog',
		'im:messenger/controller/dialog-selector',
		'im:messenger/controller/chat-creator',
		'im:messenger/controller/forward-selector',
		'im:messenger/controller/dialog-creator',
		'im:messenger/view/recent',
		'im:messenger/lib/logger',
		'im:messenger/lib/counters',
		'im:messenger/model',
		'im:messenger/view/dialog',
		'im:messenger/provider/pull',
		'im:messenger/provider/push',
		'im:messenger/lib/rest-manager',
		'im:messenger/lib/integration/mobile/communication',
		'im:messenger/lib/promotion',
		'im:messenger/lib/notifier',
		'im:messenger/lib/emitter',
		'im:chat/timer',
		'im:chat/selector/adapter/dialog-list',
		'list/selector',
		'pull/client/events',
		'statemanager/vuex',
		'statemanager/vuex-manager',
		'entity-ready',
		'type',
		'loc',
		'utils/object',
		'im:messenger/lib/ui/header/icon',
		'im:messenger/widgets/user-profile',
		'im:messenger/widgets/participants-list',
		'im:messenger/lib/ui/header',
	],
	'components' => [],
	//'packer' => [],
];