<?php

namespace Bitrix\Call\Track;

class TrackError extends \Bitrix\Call\Error
{
	public const
		EMPTY_DOWNLOAD_URL = 'EMPTY_DOWNLOAD_URL',
		DOWNLOAD_ERROR = 'DOWNLOAD_ERROR',
		SAVE_FILE_ERROR = 'SAVE_FILE_ERROR',
		DISK_ATTACH_ERROR = 'DISK_ATTACH_ERROR',
		TRACK_NOT_FOUND_ERROR = 'TRACK_NOT_FOUND_ERROR',
		TRACK_DUPLICATE_ERROR = 'TRACK_DUPLICATE_ERROR'
	;
}
